// Prototype seed data. Only the prototype adapter imports this file.
// Components must NOT import seed.ts directly - go through lib/api.

import type {
  AuditEvent,
  ClientRecord,
  Deficiency,
  Gate,
  Phase,
  PhotoEvidence,
  Project,
  SubcontractorContact,
  User,
} from "@/lib/types";

const now = Date.now();
const iso = (offsetMs: number) => new Date(now + offsetMs).toISOString();
const days = (n: number) => n * 24 * 60 * 60 * 1000;

export const seedUsers: User[] = [
  {
    id: "user-admin",
    role: "admin",
    fullName: "Sarah Chen",
    email: "sarah@titanpm.io",
    active: true,
    createdAt: iso(-days(120)),
    updatedAt: iso(-days(2)),
  },
  {
    id: "user-pm-1",
    role: "project_manager",
    fullName: "Marcus Reid",
    email: "marcus@titanpm.io",
    active: true,
    createdAt: iso(-days(90)),
    updatedAt: iso(-days(1)),
  },
  {
    id: "user-pm-2",
    role: "project_manager",
    fullName: "Priya Patel",
    email: "priya@titanpm.io",
    active: true,
    createdAt: iso(-days(60)),
    updatedAt: iso(-days(1)),
  },
];

export const seedClients: ClientRecord[] = [
  {
    id: "client-1",
    name: "New Client",
    primaryContactName: "Primary Contact",
    phone: "555-0101",
    email: "client@example.com",
    archived: false,
    createdAt: iso(-days(1)),
    updatedAt: iso(-days(1)),
  },
  {
    id: "client-2",
    name: "Acme Construction",
    primaryContactName: "John Smith",
    phone: "555-0102",
    email: "john@acmeconstruction.com",
    billingAddress: "123 Main St, Suite 100, Anytown, ST 12345",
    archived: false,
    createdAt: iso(-days(30)),
    updatedAt: iso(-days(5)),
  },
  {
    id: "client-3",
    name: "Greenfield Developers",
    primaryContactName: "Maria Garcia",
    phone: "555-0103",
    email: "maria@greenfielddev.com",
    billingAddress: "456 Oak Ave, Building B, Somewhere, ST 67890",
    notes: "Prefers sustainable materials",
    archived: false,
    createdAt: iso(-days(60)),
    updatedAt: iso(-days(10)),
  },
  {
    id: "client-4",
    name: "Summit Builders",
    primaryContactName: "David Kim",
    phone: "555-0104",
    email: "david@summitbuilders.com",
    billingAddress: "789 Pine Road, Suite 200, Mountainview, ST 54321",
    notes: "High-end residential projects",
    archived: false,
    createdAt: iso(-days(90)),
    updatedAt: iso(-days(15)),
  },
];

export const seedSubcontractors: SubcontractorContact[] = [
  {
    id: "sub-1",
    displayName: "Bob Hayes",
    companyName: "Insul-Pro",
    trade: "insulation",
    phone: "555-0201",
    email: "bob@insulpro.example",
    active: true,
    createdAt: iso(-days(100)),
    updatedAt: iso(-days(20)),
  },
  {
    id: "sub-2",
    displayName: "Tina Morales",
    companyName: "Wallcraft",
    trade: "drywall",
    phone: "555-0202",
    email: "tina@wallcraft.example",
    active: true,
    createdAt: iso(-days(100)),
    updatedAt: iso(-days(15)),
  },
  {
    id: "sub-3",
    displayName: "Jules Park",
    companyName: "Finish First",
    trade: "finishing",
    phone: "555-0203",
    email: "jules@finishfirst.example",
    active: true,
    createdAt: iso(-days(100)),
    updatedAt: iso(-days(8)),
  },
  // Insulation contractors (5 more)
  {
    id: "sub-4",
    displayName: "Mike Thompson",
    companyName: "Thermal Shield",
    trade: "insulation",
    phone: "555-0204",
    email: "mike@thermalshield.example",
    active: true,
    createdAt: iso(-days(95)),
    updatedAt: iso(-days(10)),
  },
  {
    id: "sub-5",
    displayName: "Sarah Johnson",
    companyName: "Eco Insulation",
    trade: "insulation",
    phone: "555-0205",
    email: "sarah@ecoinsulation.example",
    active: true,
    createdAt: iso(-days(90)),
    updatedAt: iso(-days(5)),
  },
  {
    id: "sub-6",
    displayName: "Dave Williams",
    companyName: "Premier Foam",
    trade: "insulation",
    phone: "555-0206",
    email: "dave@premierfoam.example",
    active: false,
    createdAt: iso(-days(85)),
    updatedAt: iso(-days(30)),
  },
  {
    id: "sub-7",
    displayName: "Lisa Chen",
    companyName: "Arctic Seal",
    trade: "insulation",
    phone: "555-0207",
    email: "lisa@arcticseal.example",
    active: true,
    createdAt: iso(-days(80)),
    updatedAt: iso(-days(3)),
  },
  {
    id: "sub-8",
    displayName: "Rob Martinez",
    companyName: "InsulMax",
    trade: "insulation",
    phone: "555-0208",
    email: "rob@insulmax.example",
    active: true,
    createdAt: iso(-days(75)),
    updatedAt: iso(-days(7)),
  },
  // Drywall contractors (5 more)
  {
    id: "sub-9",
    displayName: "Carlos Rivera",
    companyName: "Smooth Walls",
    trade: "drywall",
    phone: "555-0209",
    email: "carlos@smoothwalls.example",
    active: true,
    createdAt: iso(-days(95)),
    updatedAt: iso(-days(12)),
  },
  {
    id: "sub-10",
    displayName: "Angela Davis",
    companyName: "Pro Drywall",
    trade: "drywall",
    phone: "555-0210",
    email: "angela@prodrywall.example",
    active: true,
    createdAt: iso(-days(88)),
    updatedAt: iso(-days(4)),
  },
  {
    id: "sub-11",
    displayName: "Tom Wilson",
    companyName: "Board & Tape",
    trade: "drywall",
    phone: "555-0211",
    email: "tom@boardtape.example",
    active: false,
    createdAt: iso(-days(82)),
    updatedAt: iso(-days(25)),
  },
  {
    id: "sub-12",
    displayName: "Jenny Kim",
    companyName: "Perfect Finish Drywall",
    trade: "drywall",
    phone: "555-0212",
    email: "jenny@perfectfinish.example",
    active: true,
    createdAt: iso(-days(78)),
    updatedAt: iso(-days(6)),
  },
  {
    id: "sub-13",
    displayName: "Marc Brown",
    companyName: "Sheetrock Pros",
    trade: "drywall",
    phone: "555-0213",
    email: "marc@sheetrockpros.example",
    active: true,
    createdAt: iso(-days(72)),
    updatedAt: iso(-days(2)),
  },
  // Finishing contractors (5 more)
  {
    id: "sub-14",
    displayName: "Rachel Green",
    companyName: "Final Touch",
    trade: "finishing",
    phone: "555-0214",
    email: "rachel@finaltouch.example",
    active: true,
    createdAt: iso(-days(93)),
    updatedAt: iso(-days(8)),
  },
  {
    id: "sub-15",
    displayName: "Steve Anderson",
    companyName: "Premier Paint",
    trade: "finishing",
    phone: "555-0215",
    email: "steve@premierpaint.example",
    active: true,
    createdAt: iso(-days(87)),
    updatedAt: iso(-days(5)),
  },
  {
    id: "sub-16",
    displayName: "Maria Garcia",
    companyName: "Trim Masters",
    trade: "finishing",
    phone: "555-0216",
    email: "maria@trimmasters.example",
    active: false,
    createdAt: iso(-days(81)),
    updatedAt: iso(-days(20)),
  },
  {
    id: "sub-17",
    displayName: "Kevin Lee",
    companyName: "Elite Finishes",
    trade: "finishing",
    phone: "555-0217",
    email: "kevin@elitefinishes.example",
    active: true,
    createdAt: iso(-days(76)),
    updatedAt: iso(-days(4)),
  },
  {
    id: "sub-18",
    displayName: "Nina Patel",
    companyName: "Craftsmen Co",
    trade: "finishing",
    phone: "555-0218",
    email: "nina@craftsmenco.example",
    active: true,
    createdAt: iso(-days(70)),
    updatedAt: iso(-days(1)),
  },
];

export const seedProjects: Project[] = [];

export const seedPhases: Phase[] = [];
export const seedGates: Gate[] = [];
export const seedDeficiencies: Deficiency[] = [];
export const seedPhotos: PhotoEvidence[] = [];
export const seedAuditEvents: AuditEvent[] = [];
