// Prototype seed data. Only the prototype adapter imports this file.
// Components must NOT import seed.ts directly - go through lib/api.

import type {
  AuditEvent,
  ClientRecord,
  Deficiency,
  Gate,
  Phase,
  PhotoEvidence,
  Project,
  SubcontractorContact,
  User,
} from "@/lib/types";

const now = Date.now();
const iso = (offsetMs: number) => new Date(now + offsetMs).toISOString();
const days = (n: number) => n * 24 * 60 * 60 * 1000;

export const seedUsers: User[] = [
  {
    id: "user-admin",
    role: "admin",
    fullName: "Sarah Chen",
    email: "sarah@titanpm.io",
    active: true,
    createdAt: iso(-days(120)),
    updatedAt: iso(-days(2)),
  },
  {
    id: "user-pm-1",
    role: "project_manager",
    fullName: "Marcus Reid",
    email: "marcus@titanpm.io",
    active: true,
    createdAt: iso(-days(90)),
    updatedAt: iso(-days(1)),
  },
  {
    id: "user-pm-2",
    role: "project_manager",
    fullName: "Priya Patel",
    email: "priya@titanpm.io",
    active: true,
    createdAt: iso(-days(60)),
    updatedAt: iso(-days(1)),
  },
];

export const seedClients: ClientRecord[] = [
  {
    id: "client-1",
    name: "New Client",
    primaryContactName: "Primary Contact",
    phone: "555-0101",
    email: "client@example.com",
    archived: false,
    createdAt: iso(-days(1)),
    updatedAt: iso(-days(1)),
  },
  {
    id: "client-2",
    name: "Acme Construction",
    primaryContactName: "John Smith",
    phone: "555-0102",
    email: "john@acmeconstruction.com",
    billingAddress: "123 Main St, Suite 100, Anytown, ST 12345",
    archived: false,
    createdAt: iso(-days(30)),
    updatedAt: iso(-days(5)),
  },
  {
    id: "client-3",
    name: "Greenfield Developers",
    primaryContactName: "Maria Garcia",
    phone: "555-0103",
    email: "maria@greenfielddev.com",
    billingAddress: "456 Oak Ave, Building B, Somewhere, ST 67890",
    notes: "Prefers sustainable materials",
    archived: false,
    createdAt: iso(-days(60)),
    updatedAt: iso(-days(10)),
  },
  {
    id: "client-4",
    name: "Summit Builders",
    primaryContactName: "David Kim",
    phone: "555-0104",
    email: "david@summitbuilders.com",
    billingAddress: "789 Pine Road, Suite 200, Mountainview, ST 54321",
    notes: "High-end residential projects",
    archived: false,
    createdAt: iso(-days(90)),
    updatedAt: iso(-days(15)),
  },
];

export const seedSubcontractors: SubcontractorContact[] = [
  {
    id: "sub-1",
    displayName: "Bob Hayes",
    companyName: "Insul-Pro",
    trade: "insulation",
    phone: "555-0201",
    email: "bob@insulpro.example",
    active: true,
    createdAt: iso(-days(100)),
    updatedAt: iso(-days(20)),
  },
  {
    id: "sub-2",
    displayName: "Tina Morales",
    companyName: "Wallcraft",
    trade: "drywall",
    phone: "555-0202",
    email: "tina@wallcraft.example",
    active: true,
    createdAt: iso(-days(100)),
    updatedAt: iso(-days(15)),
  },
  {
    id: "sub-3",
    displayName: "Jules Park",
    companyName: "Finish First",
    trade: "finishing",
    phone: "555-0203",
    email: "jules@finishfirst.example",
    active: true,
    createdAt: iso(-days(100)),
    updatedAt: iso(-days(8)),
  },
  // Insulation contractors (5 more)
  {
    id: "sub-4",
    displayName: "Mike Thompson",
    companyName: "Thermal Shield",
    trade: "insulation",
    phone: "555-0204",
    email: "mike@thermalshield.example",
    active: true,
    createdAt: iso(-days(95)),
    updatedAt: iso(-days(10)),
  },
  {
    id: "sub-5",
    displayName: "Sarah Johnson",
    companyName: "Eco Insulation",
    trade: "insulation",
    phone: "555-0205",
    email: "sarah@ecoinsulation.example",
    active: true,
    createdAt: iso(-days(90)),
    updatedAt: iso(-days(5)),
  },
  {
    id: "sub-6",
    displayName: "Dave Williams",
    companyName: "Premier Foam",
    trade: "insulation",
    phone: "555-0206",
    email: "dave@premierfoam.example",
    active: false,
    createdAt: iso(-days(85)),
    updatedAt: iso(-days(30)),
  },
  {
    id: "sub-7",
    displayName: "Lisa Chen",
    companyName: "Arctic Seal",
    trade: "insulation",
    phone: "555-0207",
    email: "lisa@arcticseal.example",
    active: true,
    createdAt: iso(-days(80)),
    updatedAt: iso(-days(3)),
  },
  {
    id: "sub-8",
    displayName: "Rob Martinez",
    companyName: "InsulMax",
    trade: "insulation",
    phone: "555-0208",
    email: "rob@insulmax.example",
    active: true,
    createdAt: iso(-days(75)),
    updatedAt: iso(-days(7)),
  },
  // Drywall contractors (5 more)
  {
    id: "sub-9",
    displayName: "Carlos Rivera",
    companyName: "Smooth Walls",
    trade: "drywall",
    phone: "555-0209",
    email: "carlos@smoothwalls.example",
    active: true,
    createdAt: iso(-days(95)),
    updatedAt: iso(-days(12)),
  },
  {
    id: "sub-10",
    displayName: "Angela Davis",
    companyName: "Pro Drywall",
    trade: "drywall",
    phone: "555-0210",
    email: "angela@prodrywall.example",
    active: true,
    createdAt: iso(-days(88)),
    updatedAt: iso(-days(4)),
  },
  {
    id: "sub-11",
    displayName: "Tom Wilson",
    companyName: "Board & Tape",
    trade: "drywall",
    phone: "555-0211",
    email: "tom@boardtape.example",
    active: false,
    createdAt: iso(-days(82)),
    updatedAt: iso(-days(25)),
  },
  {
    id: "sub-12",
    displayName: "Jenny Kim",
    companyName: "Perfect Finish Drywall",
    trade: "drywall",
    phone: "555-0212",
    email: "jenny@perfectfinish.example",
    active: true,
    createdAt: iso(-days(78)),
    updatedAt: iso(-days(6)),
  },
  {
    id: "sub-13",
    displayName: "Marc Brown",
    companyName: "Sheetrock Pros",
    trade: "drywall",
    phone: "555-0213",
    email: "marc@sheetrockpros.example",
    active: true,
    createdAt: iso(-days(72)),
    updatedAt: iso(-days(2)),
  },
  // Finishing contractors (5 more)
  {
    id: "sub-14",
    displayName: "Rachel Green",
    companyName: "Final Touch",
    trade: "finishing",
    phone: "555-0214",
    email: "rachel@finaltouch.example",
    active: true,
    createdAt: iso(-days(93)),
    updatedAt: iso(-days(8)),
  },
  {
    id: "sub-15",
    displayName: "Steve Anderson",
    companyName: "Premier Paint",
    trade: "finishing",
    phone: "555-0215",
    email: "steve@premierpaint.example",
    active: true,
    createdAt: iso(-days(87)),
    updatedAt: iso(-days(5)),
  },
  {
    id: "sub-16",
    displayName: "Maria Garcia",
    companyName: "Trim Masters",
    trade: "finishing",
    phone: "555-0216",
    email: "maria@trimmasters.example",
    active: false,
    createdAt: iso(-days(81)),
    updatedAt: iso(-days(20)),
  },
  {
    id: "sub-17",
    displayName: "Kevin Lee",
    companyName: "Elite Finishes",
    trade: "finishing",
    phone: "555-0217",
    email: "kevin@elitefinishes.example",
    active: true,
    createdAt: iso(-days(76)),
    updatedAt: iso(-days(4)),
  },
  {
    id: "sub-18",
    displayName: "Nina Patel",
    companyName: "Craftsmen Co",
    trade: "finishing",
    phone: "555-0218",
    email: "nina@craftsmenco.example",
    active: true,
    createdAt: iso(-days(70)),
    updatedAt: iso(-days(1)),
  },
];

export const seedProjects: Project[] = [
  {
    id: "proj-acme-draft",
    clientId: "client-2",
    projectNumber: "ACM-1001",
    name: "Acme Ridgeview Townhomes",
    siteAddress: "101 Ridgeview Lane, Anytown, ST 12345",
    status: "draft",
    assignedProjectManagerId: "user-pm-1",
    scheduledStart: iso(days(5)),
    scheduledEnd: iso(days(65)),
    atticCheckStatus: "not_started",
    finishLevel: 3,
    createdAt: iso(-days(6)),
    updatedAt: iso(-days(6)),
  },
  {
    id: "proj-acme-active",
    clientId: "client-2",
    projectNumber: "ACM-1002",
    name: "Acme Cedar Point Villas",
    siteAddress: "220 Cedar Point Drive, Anytown, ST 12345",
    status: "active",
    assignedProjectManagerId: "user-pm-2",
    scheduledStart: iso(-days(18)),
    scheduledEnd: iso(days(28)),
    atticCheckStatus: "in_progress",
    finishLevel: 4,
    createdAt: iso(-days(25)),
    updatedAt: iso(-days(1)),
  },
  {
    id: "proj-acme-completed",
    clientId: "client-2",
    projectNumber: "ACM-1003",
    name: "Acme Willow Creek Estates",
    siteAddress: "11 Willow Creek Court, Anytown, ST 12345",
    status: "completed",
    assignedProjectManagerId: "user-pm-1",
    scheduledStart: iso(-days(70)),
    scheduledEnd: iso(-days(10)),
    atticCheckStatus: "passed",
    finishLevel: 5,
    completedAt: iso(-days(2)),
    createdAt: iso(-days(90)),
    updatedAt: iso(-days(2)),
  },
];

export const seedPhases: Phase[] = [
  // Draft project phases
  {
    id: "proj-acme-draft-phase-insulation",
    projectId: "proj-acme-draft",
    type: "insulation",
    status: "not_started",
    createdAt: iso(-days(6)),
    updatedAt: iso(-days(6)),
  },
  {
    id: "proj-acme-draft-phase-drywall",
    projectId: "proj-acme-draft",
    type: "drywall",
    status: "not_started",
    createdAt: iso(-days(6)),
    updatedAt: iso(-days(6)),
  },
  {
    id: "proj-acme-draft-phase-finishing",
    projectId: "proj-acme-draft",
    type: "finishing",
    status: "not_started",
    createdAt: iso(-days(6)),
    updatedAt: iso(-days(6)),
  },
  // Active project phases
  {
    id: "proj-acme-active-phase-insulation",
    projectId: "proj-acme-active",
    type: "insulation",
    status: "in_progress",
    scheduledStart: iso(-days(16)),
    scheduledEnd: iso(days(2)),
    assignedSubcontractorId: "sub-4",
    createdAt: iso(-days(25)),
    updatedAt: iso(-days(1)),
  },
  {
    id: "proj-acme-active-phase-drywall",
    projectId: "proj-acme-active",
    type: "drywall",
    status: "not_started",
    scheduledStart: iso(days(3)),
    scheduledEnd: iso(days(15)),
    createdAt: iso(-days(25)),
    updatedAt: iso(-days(8)),
  },
  {
    id: "proj-acme-active-phase-finishing",
    projectId: "proj-acme-active",
    type: "finishing",
    status: "not_started",
    scheduledStart: iso(days(16)),
    scheduledEnd: iso(days(28)),
    createdAt: iso(-days(25)),
    updatedAt: iso(-days(8)),
  },
  // Completed project phases
  {
    id: "proj-acme-completed-phase-insulation",
    projectId: "proj-acme-completed",
    type: "insulation",
    status: "closed",
    scheduledStart: iso(-days(68)),
    scheduledEnd: iso(-days(50)),
    closedAt: iso(-days(50)),
    assignedSubcontractorId: "sub-1",
    createdAt: iso(-days(90)),
    updatedAt: iso(-days(50)),
  },
  {
    id: "proj-acme-completed-phase-drywall",
    projectId: "proj-acme-completed",
    type: "drywall",
    status: "closed",
    scheduledStart: iso(-days(49)),
    scheduledEnd: iso(-days(30)),
    closedAt: iso(-days(30)),
    assignedSubcontractorId: "sub-2",
    createdAt: iso(-days(90)),
    updatedAt: iso(-days(30)),
  },
  {
    id: "proj-acme-completed-phase-finishing",
    projectId: "proj-acme-completed",
    type: "finishing",
    status: "closed",
    scheduledStart: iso(-days(29)),
    scheduledEnd: iso(-days(12)),
    closedAt: iso(-days(12)),
    assignedSubcontractorId: "sub-3",
    createdAt: iso(-days(90)),
    updatedAt: iso(-days(12)),
  },
];
export const seedGates: Gate[] = [
  // Draft gates
  {
    id: "proj-acme-draft-gate-insulation-site-check",
    projectId: "proj-acme-draft",
    phaseId: "proj-acme-draft-phase-insulation",
    type: "site_check",
    status: "not_started",
    requiredPhotoEvidence: true,
    createdAt: iso(-days(6)),
    updatedAt: iso(-days(6)),
  },
  {
    id: "proj-acme-draft-gate-insulation-inspection",
    projectId: "proj-acme-draft",
    phaseId: "proj-acme-draft-phase-insulation",
    type: "inspection",
    status: "not_started",
    requiredPhotoEvidence: false,
    createdAt: iso(-days(6)),
    updatedAt: iso(-days(6)),
  },
  {
    id: "proj-acme-draft-gate-drywall-site-check",
    projectId: "proj-acme-draft",
    phaseId: "proj-acme-draft-phase-drywall",
    type: "site_check",
    status: "not_started",
    requiredPhotoEvidence: true,
    createdAt: iso(-days(6)),
    updatedAt: iso(-days(6)),
  },
  {
    id: "proj-acme-draft-gate-drywall-inspection",
    projectId: "proj-acme-draft",
    phaseId: "proj-acme-draft-phase-drywall",
    type: "inspection",
    status: "not_started",
    requiredPhotoEvidence: false,
    createdAt: iso(-days(6)),
    updatedAt: iso(-days(6)),
  },
  {
    id: "proj-acme-draft-gate-finishing-site-check",
    projectId: "proj-acme-draft",
    phaseId: "proj-acme-draft-phase-finishing",
    type: "site_check",
    status: "not_started",
    requiredPhotoEvidence: true,
    createdAt: iso(-days(6)),
    updatedAt: iso(-days(6)),
  },
  {
    id: "proj-acme-draft-gate-finishing-inspection",
    projectId: "proj-acme-draft",
    phaseId: "proj-acme-draft-phase-finishing",
    type: "inspection",
    status: "not_started",
    requiredPhotoEvidence: false,
    createdAt: iso(-days(6)),
    updatedAt: iso(-days(6)),
  },
  {
    id: "proj-acme-draft-gate-attic",
    projectId: "proj-acme-draft",
    type: "attic_check",
    status: "not_started",
    requiredPhotoEvidence: true,
    createdAt: iso(-days(6)),
    updatedAt: iso(-days(6)),
  },
  // Active gates
  {
    id: "proj-acme-active-gate-insulation-site-check",
    projectId: "proj-acme-active",
    phaseId: "proj-acme-active-phase-insulation",
    type: "site_check",
    status: "passed",
    completedByUserId: "user-pm-2",
    completedAt: iso(-days(16)),
    requiredPhotoEvidence: true,
    notes: "Site check passed and prep complete.",
    createdAt: iso(-days(25)),
    updatedAt: iso(-days(16)),
  },
  {
    id: "proj-acme-active-gate-insulation-inspection",
    projectId: "proj-acme-active",
    phaseId: "proj-acme-active-phase-insulation",
    type: "inspection",
    status: "not_started",
    requiredPhotoEvidence: false,
    createdAt: iso(-days(25)),
    updatedAt: iso(-days(8)),
  },
  {
    id: "proj-acme-active-gate-drywall-site-check",
    projectId: "proj-acme-active",
    phaseId: "proj-acme-active-phase-drywall",
    type: "site_check",
    status: "not_started",
    requiredPhotoEvidence: true,
    createdAt: iso(-days(25)),
    updatedAt: iso(-days(8)),
  },
  {
    id: "proj-acme-active-gate-drywall-inspection",
    projectId: "proj-acme-active",
    phaseId: "proj-acme-active-phase-drywall",
    type: "inspection",
    status: "not_started",
    requiredPhotoEvidence: false,
    createdAt: iso(-days(25)),
    updatedAt: iso(-days(8)),
  },
  {
    id: "proj-acme-active-gate-finishing-site-check",
    projectId: "proj-acme-active",
    phaseId: "proj-acme-active-phase-finishing",
    type: "site_check",
    status: "not_started",
    requiredPhotoEvidence: true,
    createdAt: iso(-days(25)),
    updatedAt: iso(-days(8)),
  },
  {
    id: "proj-acme-active-gate-finishing-inspection",
    projectId: "proj-acme-active",
    phaseId: "proj-acme-active-phase-finishing",
    type: "inspection",
    status: "not_started",
    requiredPhotoEvidence: false,
    createdAt: iso(-days(25)),
    updatedAt: iso(-days(8)),
  },
  {
    id: "proj-acme-active-gate-attic",
    projectId: "proj-acme-active",
    type: "attic_check",
    status: "in_progress",
    requiredPhotoEvidence: true,
    callInDate: iso(-days(4)),
    callInSubcontractorId: "sub-3",
    createdAt: iso(-days(25)),
    updatedAt: iso(-days(1)),
  },
  // Completed gates
  {
    id: "proj-acme-completed-gate-insulation-site-check",
    projectId: "proj-acme-completed",
    phaseId: "proj-acme-completed-phase-insulation",
    type: "site_check",
    status: "passed",
    completedByUserId: "user-pm-1",
    completedAt: iso(-days(67)),
    requiredPhotoEvidence: true,
    createdAt: iso(-days(90)),
    updatedAt: iso(-days(67)),
  },
  {
    id: "proj-acme-completed-gate-insulation-inspection",
    projectId: "proj-acme-completed",
    phaseId: "proj-acme-completed-phase-insulation",
    type: "inspection",
    status: "passed",
    completedByUserId: "user-pm-1",
    completedAt: iso(-days(50)),
    requiredPhotoEvidence: false,
    createdAt: iso(-days(90)),
    updatedAt: iso(-days(50)),
  },
  {
    id: "proj-acme-completed-gate-drywall-site-check",
    projectId: "proj-acme-completed",
    phaseId: "proj-acme-completed-phase-drywall",
    type: "site_check",
    status: "passed",
    completedByUserId: "user-pm-1",
    completedAt: iso(-days(48)),
    requiredPhotoEvidence: true,
    createdAt: iso(-days(90)),
    updatedAt: iso(-days(48)),
  },
  {
    id: "proj-acme-completed-gate-drywall-inspection",
    projectId: "proj-acme-completed",
    phaseId: "proj-acme-completed-phase-drywall",
    type: "inspection",
    status: "passed",
    completedByUserId: "user-pm-1",
    completedAt: iso(-days(30)),
    requiredPhotoEvidence: false,
    createdAt: iso(-days(90)),
    updatedAt: iso(-days(30)),
  },
  {
    id: "proj-acme-completed-gate-finishing-site-check",
    projectId: "proj-acme-completed",
    phaseId: "proj-acme-completed-phase-finishing",
    type: "site_check",
    status: "passed",
    completedByUserId: "user-pm-1",
    completedAt: iso(-days(28)),
    requiredPhotoEvidence: true,
    createdAt: iso(-days(90)),
    updatedAt: iso(-days(28)),
  },
  {
    id: "proj-acme-completed-gate-finishing-inspection",
    projectId: "proj-acme-completed",
    phaseId: "proj-acme-completed-phase-finishing",
    type: "inspection",
    status: "passed",
    completedByUserId: "user-pm-1",
    completedAt: iso(-days(12)),
    requiredPhotoEvidence: false,
    createdAt: iso(-days(90)),
    updatedAt: iso(-days(12)),
  },
  {
    id: "proj-acme-completed-gate-attic",
    projectId: "proj-acme-completed",
    type: "attic_check",
    status: "passed",
    completedByUserId: "user-pm-1",
    completedAt: iso(-days(11)),
    requiredPhotoEvidence: true,
    callInDate: iso(-days(15)),
    callInSubcontractorId: "sub-3",
    installDate: iso(-days(11)),
    createdAt: iso(-days(90)),
    updatedAt: iso(-days(11)),
  },
];
export const seedDeficiencies: Deficiency[] = [];
export const seedPhotos: PhotoEvidence[] = [
  {
    id: "photo-acme-active-site-check-insulation",
    projectId: "proj-acme-active",
    phaseId: "proj-acme-active-phase-insulation",
    gateId: "proj-acme-active-gate-insulation-site-check",
    purpose: "site_check",
    objectKey: "seed/acme-active/site-check-insulation.jpg",
    mimeType: "image/jpeg",
    fileSizeBytes: 524288,
    status: "confirmed",
    uploadedByUserId: "user-pm-2",
    createdAt: iso(-days(16)),
    updatedAt: iso(-days(16)),
  },
  {
    id: "photo-acme-completed-attic",
    projectId: "proj-acme-completed",
    gateId: "proj-acme-completed-gate-attic",
    purpose: "attic_check",
    objectKey: "seed/acme-completed/attic-check.jpg",
    mimeType: "image/jpeg",
    fileSizeBytes: 654321,
    status: "confirmed",
    uploadedByUserId: "user-pm-1",
    createdAt: iso(-days(11)),
    updatedAt: iso(-days(11)),
  },
];
export const seedAuditEvents: AuditEvent[] = [
  {
    id: "audit-seed-create-proj-acme-draft",
    entityType: "project",
    entityId: "proj-acme-draft",
    action: "create_project",
    actorUserId: "user-admin",
    createdAt: iso(-days(6)),
  },
  {
    id: "audit-seed-create-proj-acme-active",
    entityType: "project",
    entityId: "proj-acme-active",
    action: "create_project",
    actorUserId: "user-admin",
    createdAt: iso(-days(25)),
  },
  {
    id: "audit-seed-activate-proj-acme-active",
    entityType: "project",
    entityId: "proj-acme-active",
    action: "activate_project",
    actorUserId: "user-pm-2",
    previousValue: "draft",
    nextValue: "active",
    createdAt: iso(-days(16)),
  },
  {
    id: "audit-seed-create-proj-acme-completed",
    entityType: "project",
    entityId: "proj-acme-completed",
    action: "create_project",
    actorUserId: "user-admin",
    createdAt: iso(-days(90)),
  },
  {
    id: "audit-seed-activate-proj-acme-completed",
    entityType: "project",
    entityId: "proj-acme-completed",
    action: "activate_project",
    actorUserId: "user-pm-1",
    previousValue: "draft",
    nextValue: "active",
    createdAt: iso(-days(67)),
  },
  {
    id: "audit-seed-complete-proj-acme-completed",
    entityType: "project",
    entityId: "proj-acme-completed",
    action: "complete_project",
    actorUserId: "user-pm-1",
    previousValue: "active",
    nextValue: "completed",
    createdAt: iso(-days(2)),
  },
];
