// Prototype seed data. Only the prototype adapter imports this file.
// Components must NOT import seed.ts directly - go through lib/api.

import type {
  AppNotification,
  AuditEvent,
  ClientRecord,
  Deficiency,
  EquipmentLog,
  Gate,
  InventoryPickup,
  MaterialLog,
  Phase,
  PhaseChecklistItem,
  PhotoEvidence,
  Project,
  SubcontractorContact,
  User,
} from "@/lib/types";

const now = Date.now();
const iso = (offsetMs: number) => new Date(now + offsetMs).toISOString();
const days = (n: number) => n * 24 * 60 * 60 * 1000;

export const seedUsers: User[] = [
  {
    id: "user-admin",
    role: "admin",
    fullName: "James Harrison",
    email: "james@titanpm.io",
    adminOverviewEnabled: false,
    active: true,
    createdAt: iso(-days(120)),
    updatedAt: iso(-days(2)),
  },
  {
    id: "user-admin-2",
    role: "admin",
    fullName: "Morgan Lee",
    email: "morgan@titanpm.io",
    phone: "780-555-0188",
    adminOverviewEnabled: false,
    active: true,
    createdAt: iso(-days(80)),
    updatedAt: iso(-days(3)),
  },
  {
    id: "user-pm-1",
    role: "project_manager",
    fullName: "Robert Thompson",
    email: "robert@titanpm.io",
    active: true,
    createdAt: iso(-days(90)),
    updatedAt: iso(-days(1)),
  },
  {
    id: "user-pm-2",
    role: "project_manager",
    fullName: "William Anderson",
    email: "william@titanpm.io",
    active: true,
    createdAt: iso(-days(60)),
    updatedAt: iso(-days(1)),
  },
  {
    id: "user-inventory-1",
    role: "inventory_viewer",
    fullName: "Dale Cooper",
    email: "dale@titanpm.io",
    phone: "780-555-0199",
    active: true,
    createdAt: iso(-days(30)),
    updatedAt: iso(-days(1)),
  },
  {
    id: "user-pm-3",
    role: "project_manager",
    fullName: "Priya Patel",
    email: "priya@titanpm.io",
    phone: "780-555-0177",
    active: true,
    createdAt: iso(-days(45)),
    updatedAt: iso(-days(4)),
  },
  {
    id: "user-pm-inactive",
    role: "project_manager",
    fullName: "Elliot Chen",
    email: "elliot@titanpm.io",
    active: false,
    createdAt: iso(-days(140)),
    updatedAt: iso(-days(40)),
  },
  {
    id: "user-inventory-inactive",
    role: "inventory_viewer",
    fullName: "Audrey Horne",
    email: "audrey@titanpm.io",
    phone: "780-555-0166",
    active: false,
    createdAt: iso(-days(55)),
    updatedAt: iso(-days(20)),
  },
];

export const seedClients: ClientRecord[] = [
  {
    id: "client-1",
    name: "Ventura Homes",
    primaryContactName: "John Miller",
    phone: "555-0101",
    email: "john@venturahomes.com",
    archived: false,
    createdAt: iso(-days(1)),
    updatedAt: iso(-days(1)),
  },
  {
    id: "client-2",
    name: "Fortress Developments",
    primaryContactName: "Robert Davis",
    phone: "555-0102",
    email: "robert@fortressdev.com",
    billingAddress: "123 Portage Ave, Suite 100, Winnipeg, MB R3G 0J2",
    archived: false,
    createdAt: iso(-days(30)),
    updatedAt: iso(-days(5)),
  },
  {
    id: "client-3",
    name: "Randall Homes",
    primaryContactName: "William Brown",
    phone: "555-0103",
    email: "william@randallhomes.com",
    billingAddress: "456 Pembina Hwy, Building B, Winnipeg, MB R3T 2H5",
    notes: "Prefers sustainable materials",
    archived: false,
    createdAt: iso(-days(60)),
    updatedAt: iso(-days(10)),
  },
  {
    id: "client-4",
    name: "Highland Builders",
    primaryContactName: "James Wilson",
    phone: "555-0104",
    email: "james@highlandbuilders.com",
    billingAddress: "789 Kenaston Blvd, Suite 200, Winnipeg, MB R3N 0R4",
    notes: "High-end residential projects",
    archived: false,
    createdAt: iso(-days(90)),
    updatedAt: iso(-days(15)),
  },
  {
    id: "client-5",
    name: "Prairie Lane Housing Co-op",
    primaryContactName: "Olivia Carter",
    phone: "555-0105",
    email: "olivia@prairielane.example",
    billingAddress: "18 Prairie Lane, Winnipeg, MB R3X 1K5",
    notes: "New account with no active Titan work yet; used to demonstrate empty client/project states.",
    archived: false,
    createdAt: iso(-days(12)),
    updatedAt: iso(-days(2)),
  },
  {
    id: "client-archived",
    name: "Oakridge Legacy Homes",
    primaryContactName: "Hannah Price",
    phone: "555-0106",
    email: "hannah@oakridgelegacy.example",
    billingAddress: "40 Legacy Road, Winnipeg, MB R2P 0L6",
    notes: "Archived customer retained for historical project review.",
    archived: true,
    createdAt: iso(-days(260)),
    updatedAt: iso(-days(90)),
  },
];

export const seedSubcontractors: SubcontractorContact[] = [
  {
    id: "sub-1",
    displayName: "Bob Hayes",
    companyName: "Insul-Pro",
    trade: "insulation",
    phone: "555-0201",
    email: "bob@insulpro.example",
    active: true,
    createdAt: iso(-days(100)),
    updatedAt: iso(-days(20)),
  },
  {
    id: "sub-2",
    displayName: "Tina Morales",
    companyName: "Wallcraft",
    trade: "drywall",
    phone: "555-0202",
    email: "tina@wallcraft.example",
    active: true,
    createdAt: iso(-days(100)),
    updatedAt: iso(-days(15)),
  },
  {
    id: "sub-3",
    displayName: "Jules Park",
    companyName: "Finish First",
    trade: "finishing",
    phone: "555-0203",
    email: "jules@finishfirst.example",
    active: true,
    createdAt: iso(-days(100)),
    updatedAt: iso(-days(8)),
  },
  // Insulation contractors (5 more)
  {
    id: "sub-4",
    displayName: "Mike Thompson",
    companyName: "Thermal Shield",
    trade: "insulation",
    phone: "555-0204",
    email: "mike@thermalshield.example",
    active: true,
    createdAt: iso(-days(95)),
    updatedAt: iso(-days(10)),
  },
  {
    id: "sub-5",
    displayName: "Sarah Johnson",
    companyName: "Eco Insulation",
    trade: "insulation",
    phone: "555-0205",
    email: "sarah@ecoinsulation.example",
    active: true,
    createdAt: iso(-days(90)),
    updatedAt: iso(-days(5)),
  },
  {
    id: "sub-6",
    displayName: "Dave Williams",
    companyName: "Premier Foam",
    trade: "insulation",
    phone: "555-0206",
    email: "dave@premierfoam.example",
    active: false,
    createdAt: iso(-days(85)),
    updatedAt: iso(-days(30)),
  },
  {
    id: "sub-7",
    displayName: "Lisa Chen",
    companyName: "Arctic Seal",
    trade: "insulation",
    phone: "555-0207",
    email: "lisa@arcticseal.example",
    active: true,
    createdAt: iso(-days(80)),
    updatedAt: iso(-days(3)),
  },
  {
    id: "sub-8",
    displayName: "Rob Martinez",
    companyName: "InsulMax",
    trade: "insulation",
    phone: "555-0208",
    email: "rob@insulmax.example",
    active: true,
    createdAt: iso(-days(75)),
    updatedAt: iso(-days(7)),
  },
  // Drywall contractors (5 more)
  {
    id: "sub-9",
    displayName: "Carlos Rivera",
    companyName: "Smooth Walls",
    trade: "drywall",
    phone: "555-0209",
    email: "carlos@smoothwalls.example",
    active: true,
    createdAt: iso(-days(95)),
    updatedAt: iso(-days(12)),
  },
  {
    id: "sub-10",
    displayName: "Angela Davis",
    companyName: "Pro Drywall",
    trade: "drywall",
    phone: "555-0210",
    email: "angela@prodrywall.example",
    active: true,
    createdAt: iso(-days(88)),
    updatedAt: iso(-days(4)),
  },
  {
    id: "sub-11",
    displayName: "Tom Wilson",
    companyName: "Board & Tape",
    trade: "drywall",
    phone: "555-0211",
    email: "tom@boardtape.example",
    active: false,
    createdAt: iso(-days(82)),
    updatedAt: iso(-days(25)),
  },
  {
    id: "sub-12",
    displayName: "Jenny Kim",
    companyName: "Perfect Finish Drywall",
    trade: "drywall",
    phone: "555-0212",
    email: "jenny@perfectfinish.example",
    active: true,
    createdAt: iso(-days(78)),
    updatedAt: iso(-days(6)),
  },
  {
    id: "sub-13",
    displayName: "Marc Brown",
    companyName: "Sheetrock Pros",
    trade: "drywall",
    phone: "555-0213",
    email: "marc@sheetrockpros.example",
    active: true,
    createdAt: iso(-days(72)),
    updatedAt: iso(-days(2)),
  },
  // Finishing contractors (5 more)
  {
    id: "sub-14",
    displayName: "Rachel Green",
    companyName: "Final Touch",
    trade: "finishing",
    phone: "555-0214",
    email: "rachel@finaltouch.example",
    active: true,
    createdAt: iso(-days(93)),
    updatedAt: iso(-days(8)),
  },
  {
    id: "sub-15",
    displayName: "Steve Anderson",
    companyName: "Premier Paint",
    trade: "finishing",
    phone: "555-0215",
    email: "steve@premierpaint.example",
    active: true,
    createdAt: iso(-days(87)),
    updatedAt: iso(-days(5)),
  },
  {
    id: "sub-16",
    displayName: "Maria Garcia",
    companyName: "Trim Masters",
    trade: "finishing",
    phone: "555-0216",
    email: "maria@trimmasters.example",
    active: false,
    createdAt: iso(-days(81)),
    updatedAt: iso(-days(20)),
  },
  {
    id: "sub-17",
    displayName: "Kevin Lee",
    companyName: "Elite Finishes",
    trade: "finishing",
    phone: "555-0217",
    email: "kevin@elitefinishes.example",
    active: true,
    createdAt: iso(-days(76)),
    updatedAt: iso(-days(4)),
  },
  {
    id: "sub-18",
    displayName: "Nina Patel",
    companyName: "Craftsmen Co",
    trade: "finishing",
    phone: "555-0218",
    email: "nina@craftsmenco.example",
    active: true,
    createdAt: iso(-days(70)),
    updatedAt: iso(-days(1)),
  },
];

export const seedProjects: Project[] = [
  {
    id: "proj-draft-new-home",
    clientId: "client-1",
    projectNumber: "TP-2026-001",
    name: "Ventura Oak Bend New Home",
    siteAddress: "14 Oak Bend Way, Winnipeg, MB R3Y 1A1",
    status: "draft",
    assignedProjectManagerId: "user-pm-1",
    scheduledStart: iso(days(9)),
    scheduledEnd: iso(days(69)),
    atticCheckStatus: "not_started",
    finishLevel: 3,
    notes: "Permit package is ready; waiting for client start approval.",
    notesLastEditedBy: "user-pm-1",
    notesLastEditedAt: iso(-days(2)),
    createdAt: iso(-days(4)),
    updatedAt: iso(-days(2)),
  },
  {
    id: "proj-active-insulation",
    clientId: "client-2",
    projectNumber: "TP-2026-002",
    name: "Fortress Cedar Point Villas",
    siteAddress: "220 Cedar Point Drive, Winnipeg, MB R3T 2B2",
    status: "active",
    assignedProjectManagerId: "user-pm-2",
    scheduledStart: iso(-days(18)),
    scheduledEnd: iso(days(28)),
    atticCheckStatus: "in_progress",
    finishLevel: 4,
    notes: "Insulation crew is on site; attic check has been called in.",
    notesLastEditedBy: "user-pm-2",
    notesLastEditedAt: iso(-days(1)),
    createdAt: iso(-days(25)),
    updatedAt: iso(-days(1)),
  },
  {
    id: "proj-ready-inspection",
    clientId: "client-3",
    projectNumber: "TP-2026-003",
    name: "Randall Prairie Duplex",
    siteAddress: "88 Prairie Vista Road, Winnipeg, MB R3X 0C3",
    status: "active",
    assignedProjectManagerId: "user-pm-1",
    scheduledStart: iso(-days(32)),
    scheduledEnd: iso(days(18)),
    atticCheckStatus: "in_progress",
    finishLevel: 4,
    notes: "Drywall is ready for inspection; schedule inspector this week.",
    notesLastEditedBy: "user-pm-1",
    notesLastEditedAt: iso(-days(1)),
    createdAt: iso(-days(40)),
    updatedAt: iso(-days(1)),
  },
  {
    id: "proj-site-blocked",
    clientId: "client-4",
    projectNumber: "TP-2026-004",
    name: "Highland Lakeview Custom",
    siteAddress: "502 Lakeview Crescent, Winnipeg, MB R2J 4D4",
    status: "active",
    assignedProjectManagerId: "user-pm-2",
    scheduledStart: iso(-days(26)),
    scheduledEnd: iso(days(36)),
    atticCheckStatus: "blocked",
    finishLevel: 5,
    notes: "Drywall delivery blocked by standing water in service lane.",
    notesLastEditedBy: "user-pm-2",
    notesLastEditedAt: iso(-days(1)),
    createdAt: iso(-days(34)),
    updatedAt: iso(-days(1)),
  },
  {
    id: "proj-failed-inspection",
    clientId: "client-2",
    projectNumber: "TP-2026-005",
    name: "Fortress Willow Park Rowhomes",
    siteAddress: "117 Willow Park Gate, Winnipeg, MB R3K 2E5",
    status: "active",
    assignedProjectManagerId: "user-pm-1",
    scheduledStart: iso(-days(22)),
    scheduledEnd: iso(-days(5)),
    atticCheckStatus: "in_progress",
    finishLevel: 3,
    notes: "Inspection failed on vapor barrier continuity; rework assigned.",
    notesLastEditedBy: "user-pm-1",
    notesLastEditedAt: iso(-days(1)),
    createdAt: iso(-days(31)),
    updatedAt: iso(-days(1)),
  },
  {
    id: "proj-deficiency-rework",
    clientId: "client-3",
    projectNumber: "TP-2026-006",
    name: "Randall North Rework",
    siteAddress: "64 North Meadow Lane, Winnipeg, MB R3W 1F6",
    status: "active",
    assignedProjectManagerId: "user-pm-2",
    scheduledStart: iso(-days(38)),
    scheduledEnd: iso(days(12)),
    atticCheckStatus: "in_progress",
    finishLevel: 4,
    notes: "Failed inspection was corrected; phase is back in rework before final pass.",
    notesLastEditedBy: "user-pm-2",
    notesLastEditedAt: iso(-days(2)),
    createdAt: iso(-days(48)),
    updatedAt: iso(-days(15)),
  },
  {
    id: "proj-finishing-active",
    clientId: "client-4",
    projectNumber: "TP-2026-007",
    name: "Highland Riverbend Finishing",
    siteAddress: "9 Riverbend Place, Winnipeg, MB R2M 5G7",
    status: "active",
    assignedProjectManagerId: "user-pm-1",
    scheduledStart: iso(-days(52)),
    scheduledEnd: iso(days(8)),
    atticCheckStatus: "in_progress",
    finishLevel: 5,
    notes: "Finish level five walkthrough planned with client representative.",
    notesLastEditedBy: "user-pm-1",
    notesLastEditedAt: iso(-days(3)),
    createdAt: iso(-days(60)),
    updatedAt: iso(-days(3)),
  },
  {
    id: "proj-ready-complete",
    clientId: "client-2",
    projectNumber: "TP-2026-008",
    name: "Fortress Ready Complete Bungalow",
    siteAddress: "711 Ready Street, Winnipeg, MB R3L 0H8",
    status: "completed",
    assignedProjectManagerId: "user-pm-2",
    scheduledStart: iso(-days(68)),
    scheduledEnd: iso(-days(2)),
    atticCheckStatus: "passed",
    finishLevel: 4,
    completedAt: iso(-days(1)),
    notes: "All requirements are complete; ready to archive.",
    notesLastEditedBy: "user-pm-2",
    notesLastEditedAt: iso(-days(1)),
    createdAt: iso(-days(76)),
    updatedAt: iso(-days(1)),
  },
  {
    id: "proj-completed-archiveable",
    clientId: "client-3",
    projectNumber: "TP-2026-009",
    name: "Randall Completed Estate",
    siteAddress: "305 Estate Row, Winnipeg, MB R3P 2J9",
    status: "completed",
    assignedProjectManagerId: "user-pm-1",
    scheduledStart: iso(-days(96)),
    scheduledEnd: iso(-days(16)),
    atticCheckStatus: "passed",
    finishLevel: 5,
    completedAt: iso(-days(10)),
    notes: "Client sign-off complete; ready for archive.",
    notesLastEditedBy: "user-pm-1",
    notesLastEditedAt: iso(-days(10)),
    createdAt: iso(-days(106)),
    updatedAt: iso(-days(10)),
  },
  {
    id: "proj-archived-history",
    clientId: "client-4",
    projectNumber: "TP-2026-010",
    name: "Highland Archived Timberline",
    siteAddress: "43 Timberline Trail, Winnipeg, MB R2C 4K0",
    status: "archived",
    assignedProjectManagerId: "user-pm-2",
    scheduledStart: iso(-days(150)),
    scheduledEnd: iso(-days(82)),
    atticCheckStatus: "passed",
    finishLevel: 4,
    completedAt: iso(-days(82)),
    notes: "Archived historical project retained for activity and detail review.",
    notesLastEditedBy: "user-pm-2",
    notesLastEditedAt: iso(-days(80)),
    createdAt: iso(-days(160)),
    updatedAt: iso(-days(80)),
  },
  {
    id: "proj-active-not-started",
    clientId: "client-5",
    projectNumber: "TP-2026-011",
    name: "Prairie Lane Activation",
    siteAddress: "18 Prairie Lane, Winnipeg, MB R3X 1K5",
    status: "active",
    scheduledStart: iso(days(1)),
    scheduledEnd: iso(days(44)),
    atticCheckStatus: "not_started",
    finishLevel: 3,
    notes: "Activated job waiting for kickoff; intentionally unassigned to demonstrate admin triage.",
    notesLastEditedBy: "user-admin",
    notesLastEditedAt: iso(-days(1)),
    createdAt: iso(-days(3)),
    updatedAt: iso(-days(1)),
  },
  {
    id: "proj-overdue-clean",
    clientId: "client-1",
    projectNumber: "TP-2026-012",
    name: "Ventura Elm Overdue Closeout",
    siteAddress: "61 Elm Grove, Winnipeg, MB R3M 2L1",
    status: "active",
    assignedProjectManagerId: "user-pm-1",
    scheduledStart: iso(-days(36)),
    scheduledEnd: iso(-days(3)),
    atticCheckStatus: "passed",
    finishLevel: 4,
    notes: "Clean overdue project with no blockers; needs schedule reforecast or closeout.",
    notesLastEditedBy: "user-pm-1",
    notesLastEditedAt: iso(-days(1)),
    createdAt: iso(-days(42)),
    updatedAt: iso(-days(1)),
  },
  {
    id: "proj-stale-clean",
    clientId: "client-3",
    projectNumber: "TP-2026-013",
    name: "Randall Quiet Stale Build",
    siteAddress: "144 Quiet Bay, Winnipeg, MB R3W 2N4",
    status: "active",
    assignedProjectManagerId: "user-pm-2",
    scheduledStart: iso(-days(24)),
    scheduledEnd: iso(days(30)),
    atticCheckStatus: "passed",
    finishLevel: 3,
    notes: "No blockers or failures; intentionally stale to demonstrate command center aging.",
    notesLastEditedBy: "user-pm-2",
    notesLastEditedAt: iso(-days(20)),
    createdAt: iso(-days(30)),
    updatedAt: iso(-days(20)),
  },
  {
    id: "proj-ready-finishing-inspection",
    clientId: "client-4",
    projectNumber: "TP-2026-014",
    name: "Highland Sage Inspection",
    siteAddress: "27 Sage Creek Bend, Winnipeg, MB R3X 0M9",
    status: "active",
    assignedProjectManagerId: "user-pm-2",
    scheduledStart: iso(-days(44)),
    scheduledEnd: iso(days(14)),
    atticCheckStatus: "passed",
    finishLevel: 5,
    notes: "Second ready inspection example to make bottleneck insights visible.",
    notesLastEditedBy: "user-pm-2",
    notesLastEditedAt: iso(-days(4)),
    createdAt: iso(-days(50)),
    updatedAt: iso(-days(4)),
  },
  {
    id: "proj-archived-legacy",
    clientId: "client-archived",
    projectNumber: "TP-2025-044",
    name: "Oakridge Archived Manor",
    siteAddress: "40 Legacy Road, Winnipeg, MB R2P 0L6",
    status: "archived",
    assignedProjectManagerId: "user-pm-1",
    scheduledStart: iso(-days(230)),
    scheduledEnd: iso(-days(170)),
    atticCheckStatus: "passed",
    finishLevel: 4,
    completedAt: iso(-days(168)),
    notes: "Archived project tied to an archived client for history demos.",
    notesLastEditedBy: "user-admin",
    notesLastEditedAt: iso(-days(120)),
    createdAt: iso(-days(240)),
    updatedAt: iso(-days(120)),
  },
];

const phaseTypes = ["insulation", "drywall", "finishing"] as const;

const phaseSubcontractors = {
  insulation: "sub-4",
  drywall: "sub-9",
  finishing: "sub-14",
} as const;

const phaseWindows = {
  insulation: { start: 0, end: 10 },
  drywall: { start: 8, end: 20 },
  finishing: { start: 21, end: 33 },
} as const;

type PhaseSeed = {
  status: Phase["status"];
  assignedSubcontractorId?: string;
  scheduledStart?: string;
  scheduledEnd?: string;
  closedAt?: string;
  updatedAt?: string;
};

type GateSeed = Partial<Pick<Gate, "status" | "completedByUserId" | "completedAt" | "notes" | "callInDate" | "installDate" | "callInSubcontractorId" | "updatedAt">>;

type Scenario = {
  projectId: string;
  ageDays: number;
  phases: Record<(typeof phaseTypes)[number], PhaseSeed>;
  gates?: Record<string, GateSeed>;
};

const scenarios: Scenario[] = [
  {
    projectId: "proj-draft-new-home",
    ageDays: 4,
    phases: {
      insulation: { status: "not_started" },
      drywall: { status: "not_started" },
      finishing: { status: "not_started" },
    },
  },
  {
    projectId: "proj-active-insulation",
    ageDays: 25,
    phases: {
      insulation: {
        status: "in_progress",
        assignedSubcontractorId: "sub-4",
        scheduledStart: iso(-days(16)),
        scheduledEnd: iso(days(2)),
        updatedAt: iso(-days(1)),
      },
      drywall: { status: "not_started", scheduledStart: iso(days(3)), scheduledEnd: iso(days(15)) },
      finishing: { status: "not_started", scheduledStart: iso(days(16)), scheduledEnd: iso(days(28)) },
    },
    gates: {
      "insulation-site_check": {
        status: "passed",
        completedByUserId: "user-pm-2",
        completedAt: iso(-days(16)),
        notes: "Insulation site check passed and prep is complete.",
        updatedAt: iso(-days(16)),
      },
      attic: {
        status: "in_progress",
        callInDate: iso(-days(4)),
        callInSubcontractorId: "sub-14",
        updatedAt: iso(-days(1)),
      },
    },
  },
  {
    projectId: "proj-ready-inspection",
    ageDays: 40,
    phases: {
      insulation: { status: "closed", assignedSubcontractorId: "sub-1", closedAt: iso(-days(18)) },
      drywall: {
        status: "ready_for_inspection",
        assignedSubcontractorId: "sub-9",
        scheduledStart: iso(-days(12)),
        scheduledEnd: new Date(now).toISOString().slice(0, 10),
        updatedAt: iso(-days(5)),
      },
      finishing: { status: "not_started", scheduledStart: iso(days(3)), scheduledEnd: iso(days(18)) },
    },
    gates: {
      "insulation-site_check": { status: "passed", completedByUserId: "user-pm-1", completedAt: iso(-days(29)) },
      "insulation-inspection": { status: "passed", completedByUserId: "user-pm-1", completedAt: iso(-days(18)) },
      "drywall-site_check": { status: "passed", completedByUserId: "user-pm-1", completedAt: iso(-days(12)) },
      attic: { status: "in_progress", callInDate: iso(-days(2)), callInSubcontractorId: "sub-15" },
    },
  },
  {
    projectId: "proj-site-blocked",
    ageDays: 34,
    phases: {
      insulation: { status: "closed", assignedSubcontractorId: "sub-5", closedAt: iso(-days(14)) },
      drywall: {
        status: "blocked",
        assignedSubcontractorId: "sub-9",
        scheduledStart: iso(-days(8)),
        scheduledEnd: iso(days(6)),
        updatedAt: iso(-days(1)),
      },
      finishing: { status: "not_started", scheduledStart: iso(days(8)), scheduledEnd: iso(days(28)) },
    },
    gates: {
      "insulation-site_check": { status: "passed", completedByUserId: "user-pm-2", completedAt: iso(-days(24)) },
      "insulation-inspection": { status: "passed", completedByUserId: "user-pm-2", completedAt: iso(-days(14)) },
      "drywall-site_check": {
        status: "blocked",
        notes: "Standing water blocks material delivery.",
        updatedAt: iso(-days(1)),
      },
      attic: { status: "blocked", notes: "Attic access is blocked until drywall delivery is cleared." },
    },
  },
  {
    projectId: "proj-failed-inspection",
    ageDays: 31,
    phases: {
      insulation: {
        status: "blocked",
        assignedSubcontractorId: "sub-6",
        scheduledStart: iso(-days(21)),
        scheduledEnd: iso(-days(5)),
        updatedAt: iso(-days(1)),
      },
      drywall: { status: "not_started" },
      finishing: { status: "not_started" },
    },
    gates: {
      "insulation-site_check": { status: "passed", completedByUserId: "user-pm-1", completedAt: iso(-days(18)) },
      "insulation-inspection": {
        status: "failed",
        completedByUserId: "user-pm-1",
        completedAt: iso(-days(1)),
        notes: "Vapor barrier discontinuity at west wall.",
        updatedAt: iso(-days(1)),
      },
      attic: { status: "in_progress", callInDate: iso(-days(3)), callInSubcontractorId: "sub-14" },
    },
  },
  {
    projectId: "proj-deficiency-rework",
    ageDays: 48,
    phases: {
      insulation: {
        status: "in_progress",
        assignedSubcontractorId: "sub-7",
        scheduledStart: iso(-days(30)),
        scheduledEnd: iso(-days(8)),
        updatedAt: iso(-days(2)),
      },
      drywall: { status: "not_started", scheduledStart: iso(days(1)), scheduledEnd: iso(days(10)) },
      finishing: { status: "not_started", scheduledStart: iso(days(11)), scheduledEnd: iso(days(12)) },
    },
    gates: {
      "insulation-site_check": { status: "passed", completedByUserId: "user-pm-2", completedAt: iso(-days(30)) },
      "insulation-inspection": {
        status: "in_progress",
        completedByUserId: "user-pm-2",
        completedAt: iso(-days(7)),
        notes: "Rework verified; awaiting final inspection pass.",
        updatedAt: iso(-days(2)),
      },
      attic: { status: "in_progress", callInDate: iso(-days(3)), callInSubcontractorId: "sub-17" },
    },
  },
  {
    projectId: "proj-finishing-active",
    ageDays: 60,
    phases: {
      insulation: { status: "closed", assignedSubcontractorId: "sub-1", closedAt: iso(-days(38)) },
      drywall: { status: "closed", assignedSubcontractorId: "sub-10", closedAt: iso(-days(16)) },
      finishing: {
        status: "in_progress",
        assignedSubcontractorId: "sub-17",
        scheduledStart: iso(-days(15)),
        scheduledEnd: iso(days(8)),
        updatedAt: iso(-days(3)),
      },
    },
    gates: {
      "insulation-site_check": { status: "passed", completedByUserId: "user-pm-1", completedAt: iso(-days(52)) },
      "insulation-inspection": { status: "passed", completedByUserId: "user-pm-1", completedAt: iso(-days(38)) },
      "drywall-site_check": { status: "passed", completedByUserId: "user-pm-1", completedAt: iso(-days(30)) },
      "drywall-inspection": { status: "passed", completedByUserId: "user-pm-1", completedAt: iso(-days(16)) },
      "finishing-site_check": { status: "passed", completedByUserId: "user-pm-1", completedAt: iso(-days(15)) },
      attic: { status: "in_progress", callInDate: iso(-days(6)), callInSubcontractorId: "sub-18" },
    },
  },
  {
    projectId: "proj-ready-complete",
    ageDays: 76,
    phases: {
      insulation: { status: "closed", assignedSubcontractorId: "sub-4", closedAt: iso(-days(48)) },
      drywall: { status: "closed", assignedSubcontractorId: "sub-11", closedAt: iso(-days(24)) },
      finishing: { status: "closed", assignedSubcontractorId: "sub-18", closedAt: iso(-days(3)) },
    },
    gates: {
      "insulation-site_check": { status: "passed", completedByUserId: "user-pm-2", completedAt: iso(-days(62)) },
      "insulation-inspection": { status: "passed", completedByUserId: "user-pm-2", completedAt: iso(-days(48)) },
      "drywall-site_check": { status: "passed", completedByUserId: "user-pm-2", completedAt: iso(-days(36)) },
      "drywall-inspection": { status: "passed", completedByUserId: "user-pm-2", completedAt: iso(-days(24)) },
      "finishing-site_check": { status: "passed", completedByUserId: "user-pm-2", completedAt: iso(-days(18)) },
      "finishing-inspection": { status: "passed", completedByUserId: "user-pm-2", completedAt: iso(-days(3)) },
      attic: {
        status: "passed",
        completedByUserId: "user-pm-2",
        completedAt: iso(-days(3)),
        callInDate: iso(-days(8)),
        callInSubcontractorId: "sub-14",
        installDate: iso(-days(3)),
      },
    },
  },
  {
    projectId: "proj-completed-archiveable",
    ageDays: 106,
    phases: {
      insulation: { status: "closed", assignedSubcontractorId: "sub-5", closedAt: iso(-days(72)) },
      drywall: { status: "closed", assignedSubcontractorId: "sub-12", closedAt: iso(-days(44)) },
      finishing: { status: "closed", assignedSubcontractorId: "sub-15", closedAt: iso(-days(16)) },
    },
    gates: {
      "insulation-site_check": { status: "passed", completedByUserId: "user-pm-1", completedAt: iso(-days(90)) },
      "insulation-inspection": { status: "passed", completedByUserId: "user-pm-1", completedAt: iso(-days(72)) },
      "drywall-site_check": { status: "passed", completedByUserId: "user-pm-1", completedAt: iso(-days(56)) },
      "drywall-inspection": { status: "passed", completedByUserId: "user-pm-1", completedAt: iso(-days(44)) },
      "finishing-site_check": { status: "passed", completedByUserId: "user-pm-1", completedAt: iso(-days(28)) },
      "finishing-inspection": { status: "passed", completedByUserId: "user-pm-1", completedAt: iso(-days(16)) },
      attic: {
        status: "passed",
        completedByUserId: "user-pm-1",
        completedAt: iso(-days(15)),
        callInDate: iso(-days(20)),
        callInSubcontractorId: "sub-15",
        installDate: iso(-days(15)),
      },
    },
  },
  {
    projectId: "proj-archived-history",
    ageDays: 160,
    phases: {
      insulation: { status: "closed", assignedSubcontractorId: "sub-6", closedAt: iso(-days(128)) },
      drywall: { status: "closed", assignedSubcontractorId: "sub-13", closedAt: iso(-days(104)) },
      finishing: { status: "closed", assignedSubcontractorId: "sub-16", closedAt: iso(-days(84)) },
    },
    gates: {
      "insulation-site_check": { status: "passed", completedByUserId: "user-pm-2", completedAt: iso(-days(146)) },
      "insulation-inspection": { status: "passed", completedByUserId: "user-pm-2", completedAt: iso(-days(128)) },
      "drywall-site_check": { status: "passed", completedByUserId: "user-pm-2", completedAt: iso(-days(116)) },
      "drywall-inspection": { status: "passed", completedByUserId: "user-pm-2", completedAt: iso(-days(104)) },
      "finishing-site_check": { status: "passed", completedByUserId: "user-pm-2", completedAt: iso(-days(92)) },
      "finishing-inspection": { status: "passed", completedByUserId: "user-pm-2", completedAt: iso(-days(84)) },
      attic: {
        status: "passed",
        completedByUserId: "user-pm-2",
        completedAt: iso(-days(83)),
        callInDate: iso(-days(88)),
        callInSubcontractorId: "sub-17",
        installDate: iso(-days(83)),
      },
    },
  },
  {
    projectId: "proj-active-not-started",
    ageDays: 3,
    phases: {
      insulation: { status: "not_started", scheduledStart: iso(days(1)), scheduledEnd: iso(days(12)) },
      drywall: { status: "not_started", scheduledStart: iso(days(13)), scheduledEnd: iso(days(28)) },
      finishing: { status: "not_started", scheduledStart: iso(days(29)), scheduledEnd: iso(days(44)) },
    },
  },
  {
    projectId: "proj-overdue-clean",
    ageDays: 42,
    phases: {
      insulation: { status: "closed", assignedSubcontractorId: "sub-4", closedAt: iso(-days(20)) },
      drywall: { status: "closed", assignedSubcontractorId: "sub-9", closedAt: iso(-days(7)) },
      finishing: {
        status: "in_progress",
        assignedSubcontractorId: "sub-14",
        scheduledStart: iso(-days(8)),
        scheduledEnd: iso(-days(3)),
        updatedAt: iso(-days(1)),
      },
    },
    gates: {
      "insulation-site_check": { status: "passed", completedByUserId: "user-pm-1", completedAt: iso(-days(34)) },
      "insulation-inspection": { status: "passed", completedByUserId: "user-pm-1", completedAt: iso(-days(20)) },
      "drywall-site_check": { status: "passed", completedByUserId: "user-pm-1", completedAt: iso(-days(18)) },
      "drywall-inspection": { status: "passed", completedByUserId: "user-pm-1", completedAt: iso(-days(7)) },
      "finishing-site_check": { status: "passed", completedByUserId: "user-pm-1", completedAt: iso(-days(8)) },
      attic: {
        status: "passed",
        completedByUserId: "user-pm-1",
        completedAt: iso(-days(6)),
        callInDate: iso(-days(10)),
        callInSubcontractorId: "sub-14",
        installDate: iso(-days(6)),
      },
    },
  },
  {
    projectId: "proj-stale-clean",
    ageDays: 30,
    phases: {
      insulation: {
        status: "in_progress",
        assignedSubcontractorId: "sub-5",
        scheduledStart: iso(-days(24)),
        scheduledEnd: iso(days(4)),
        updatedAt: iso(-days(20)),
      },
      drywall: { status: "not_started", scheduledStart: iso(days(5)), scheduledEnd: iso(days(18)) },
      finishing: { status: "not_started", scheduledStart: iso(days(19)), scheduledEnd: iso(days(30)) },
    },
    gates: {
      "insulation-site_check": { status: "passed", completedByUserId: "user-pm-2", completedAt: iso(-days(24)) },
      attic: {
        status: "passed",
        completedByUserId: "user-pm-2",
        completedAt: iso(-days(22)),
        callInDate: iso(-days(24)),
        callInSubcontractorId: "sub-17",
        installDate: iso(-days(22)),
      },
    },
  },
  {
    projectId: "proj-ready-finishing-inspection",
    ageDays: 50,
    phases: {
      insulation: { status: "closed", assignedSubcontractorId: "sub-7", closedAt: iso(-days(28)) },
      drywall: { status: "closed", assignedSubcontractorId: "sub-12", closedAt: iso(-days(10)) },
      finishing: {
        status: "ready_for_inspection",
        assignedSubcontractorId: "sub-18",
        scheduledStart: iso(-days(9)),
        scheduledEnd: iso(days(14)),
        updatedAt: iso(-days(4)),
      },
    },
    gates: {
      "insulation-site_check": { status: "passed", completedByUserId: "user-pm-2", completedAt: iso(-days(38)) },
      "insulation-inspection": { status: "passed", completedByUserId: "user-pm-2", completedAt: iso(-days(28)) },
      "drywall-site_check": { status: "passed", completedByUserId: "user-pm-2", completedAt: iso(-days(22)) },
      "drywall-inspection": { status: "passed", completedByUserId: "user-pm-2", completedAt: iso(-days(10)) },
      "finishing-site_check": { status: "passed", completedByUserId: "user-pm-2", completedAt: iso(-days(9)) },
      attic: {
        status: "passed",
        completedByUserId: "user-pm-2",
        completedAt: iso(-days(8)),
        callInDate: iso(-days(12)),
        callInSubcontractorId: "sub-18",
        installDate: iso(-days(8)),
      },
    },
  },
  {
    projectId: "proj-archived-legacy",
    ageDays: 240,
    phases: {
      insulation: { status: "closed", assignedSubcontractorId: "sub-5", closedAt: iso(-days(214)) },
      drywall: { status: "closed", assignedSubcontractorId: "sub-10", closedAt: iso(-days(190)) },
      finishing: { status: "closed", assignedSubcontractorId: "sub-15", closedAt: iso(-days(171)) },
    },
    gates: {
      "insulation-site_check": { status: "passed", completedByUserId: "user-pm-1", completedAt: iso(-days(224)) },
      "insulation-inspection": { status: "passed", completedByUserId: "user-pm-1", completedAt: iso(-days(214)) },
      "drywall-site_check": { status: "passed", completedByUserId: "user-pm-1", completedAt: iso(-days(204)) },
      "drywall-inspection": { status: "passed", completedByUserId: "user-pm-1", completedAt: iso(-days(190)) },
      "finishing-site_check": { status: "passed", completedByUserId: "user-pm-1", completedAt: iso(-days(178)) },
      "finishing-inspection": { status: "passed", completedByUserId: "user-pm-1", completedAt: iso(-days(171)) },
      attic: {
        status: "passed",
        completedByUserId: "user-pm-1",
        completedAt: iso(-days(170)),
        callInDate: iso(-days(176)),
        callInSubcontractorId: "sub-15",
        installDate: iso(-days(170)),
      },
    },
  },
];

function scenarioFor(projectId: string) {
  const scenario = scenarios.find((item) => item.projectId === projectId);
  if (!scenario) throw new Error(`Missing seed scenario for ${projectId}`);
  return scenario;
}

function defaultPhaseDates(projectId: string, type: (typeof phaseTypes)[number], ageDays: number) {
  const project = seedProjects.find((item) => item.id === projectId);
  const window = phaseWindows[type];
  const projectStart = project?.scheduledStart ? new Date(project.scheduledStart).getTime() : now - days(ageDays);
  
  let startOffset: number = window.start;
  let endOffset: number = window.end;
  
  // Clamp to project boundaries if project has dates
  if (project?.scheduledStart && project?.scheduledEnd) {
    const projectEnd = new Date(project.scheduledEnd).getTime();
    const projectDurationDays = Math.floor((projectEnd - projectStart) / days(1));
    
    // Ensure phase end doesn't exceed project end
    if (endOffset > projectDurationDays) {
      endOffset = projectDurationDays;
    }

    // Ensure phase start doesn't exceed project end, and maintain at least 1 day duration
    if (startOffset >= endOffset) {
      startOffset = Math.max(0, endOffset - 1);
    }
  }
  
  return {
    scheduledStart: iso(projectStart - now + days(startOffset)),
    scheduledEnd: iso(projectStart - now + days(endOffset)),
  };
}

export const seedPhases: Phase[] = seedProjects.flatMap((project) => {
  const scenario = scenarioFor(project.id);
  return phaseTypes.map((type) => {
    const phase = scenario.phases[type];
    const dates = defaultPhaseDates(project.id, type, scenario.ageDays);
    const createdAt = iso(-days(scenario.ageDays));
    const updatedAt = phase.updatedAt ?? phase.closedAt ?? project.updatedAt;
    return {
      id: `${project.id}-phase-${type}`,
      projectId: project.id,
      type,
      status: phase.status,
      scheduledStart: phase.scheduledStart ?? dates.scheduledStart,
      scheduledEnd: phase.scheduledEnd ?? dates.scheduledEnd,
      closedAt: phase.closedAt,
      assignedSubcontractorId: phase.assignedSubcontractorId ?? (phase.status === "not_started" ? undefined : phaseSubcontractors[type]),
      createdAt,
      updatedAt,
    };
  });
});

export const seedChecklistItems: PhaseChecklistItem[] = [
  {
    id: "checklist-proj-active-insulation-insulation-baffles",
    projectId: "proj-active-insulation",
    phaseId: "proj-active-insulation-phase-insulation",
    text: "Confirm attic baffles are installed at all eaves",
    completed: true,
    createdAt: iso(-days(15)),
    updatedAt: iso(-days(14)),
  },
  {
    id: "checklist-proj-active-insulation-insulation-vapor-barrier",
    projectId: "proj-active-insulation",
    phaseId: "proj-active-insulation-phase-insulation",
    text: "Verify vapor barrier lap seals at exterior corners",
    completed: false,
    createdAt: iso(-days(14)),
    updatedAt: iso(-days(2)),
  },
  {
    id: "checklist-proj-ready-inspection-drywall-screw-pattern",
    projectId: "proj-ready-inspection",
    phaseId: "proj-ready-inspection-phase-drywall",
    text: "Confirm screw pattern photos are uploaded",
    completed: true,
    createdAt: iso(-days(11)),
    updatedAt: iso(-days(6)),
  },
  {
    id: "checklist-proj-ready-inspection-drywall-call-inspector",
    projectId: "proj-ready-inspection",
    phaseId: "proj-ready-inspection-phase-drywall",
    text: "Call inspector with board count and access notes",
    completed: false,
    createdAt: iso(-days(6)),
    updatedAt: iso(-days(5)),
  },
  {
    id: "checklist-proj-site-blocked-drywall-delivery-access",
    projectId: "proj-site-blocked",
    phaseId: "proj-site-blocked-phase-drywall",
    text: "Reconfirm delivery access after service lane dries",
    completed: false,
    createdAt: iso(-days(7)),
    updatedAt: iso(-days(1)),
  },
  {
    id: "checklist-proj-finishing-active-finishing-mask-cabinets",
    projectId: "proj-finishing-active",
    phaseId: "proj-finishing-active-phase-finishing",
    text: "Mask completed cabinet boxes before final skim",
    completed: true,
    createdAt: iso(-days(13)),
    updatedAt: iso(-days(12)),
  },
  {
    id: "checklist-proj-finishing-active-finishing-walkthrough",
    projectId: "proj-finishing-active",
    phaseId: "proj-finishing-active-phase-finishing",
    text: "Walk level-five touch-up list with client representative",
    completed: false,
    createdAt: iso(-days(4)),
    updatedAt: iso(-days(3)),
  },
  {
    id: "checklist-proj-overdue-clean-finishing-sanding",
    projectId: "proj-overdue-clean",
    phaseId: "proj-overdue-clean-phase-finishing",
    text: "Confirm final sanding areas are dust free",
    completed: false,
    createdAt: iso(-days(5)),
    updatedAt: iso(-days(1)),
  },
  {
    id: "checklist-proj-stale-clean-insulation-poly",
    projectId: "proj-stale-clean",
    phaseId: "proj-stale-clean-phase-insulation",
    text: "Recheck poly seal at rim joist transitions",
    completed: false,
    createdAt: iso(-days(22)),
    updatedAt: iso(-days(20)),
  },
];

export const seedMaterialLogs: MaterialLog[] = [
  {
    id: "material-proj-active-insulation-insulation-r20-batt",
    projectId: "proj-active-insulation",
    phaseId: "proj-active-insulation-phase-insulation",
    itemKey: "r20_batt",
    quantity: 32,
    updatedAt: iso(-days(2)),
  },
  {
    id: "material-proj-active-insulation-insulation-r22-batt",
    projectId: "proj-active-insulation",
    phaseId: "proj-active-insulation-phase-insulation",
    itemKey: "r22_batt",
    quantity: 18,
    updatedAt: iso(-days(2)),
  },
  {
    id: "material-proj-ready-inspection-drywall-half-inch-regular-board",
    projectId: "proj-ready-inspection",
    phaseId: "proj-ready-inspection-phase-drywall",
    itemKey: "half_inch_regular_board",
    quantity: 96,
    updatedAt: iso(-days(3)),
  },
  {
    id: "material-proj-ready-inspection-drywall-type-x-board",
    projectId: "proj-ready-inspection",
    phaseId: "proj-ready-inspection-phase-drywall",
    itemKey: "type_x_board",
    quantity: 24,
    updatedAt: iso(-days(3)),
  },
  {
    id: "material-proj-finishing-active-finishing-all-purpose-mud",
    projectId: "proj-finishing-active",
    phaseId: "proj-finishing-active-phase-finishing",
    itemKey: "all_purpose_mud",
    quantity: 14,
    updatedAt: iso(-days(1)),
  },
  {
    id: "material-proj-finishing-active-finishing-outside-corner-bead",
    projectId: "proj-finishing-active",
    phaseId: "proj-finishing-active-phase-finishing",
    itemKey: "outside_corner_bead",
    quantity: 40,
    updatedAt: iso(-days(1)),
  },
  {
    id: "material-proj-active-insulation-insulation-acoustic-sealant",
    projectId: "proj-active-insulation",
    phaseId: "proj-active-insulation-phase-insulation",
    itemKey: "acoustic_sealant",
    quantity: 9,
    updatedAt: iso(-days(1)),
  },
  {
    id: "material-proj-active-insulation-insulation-six-mil-poly-rolls",
    projectId: "proj-active-insulation",
    phaseId: "proj-active-insulation-phase-insulation",
    itemKey: "six_mil_poly_rolls",
    quantity: 5,
    updatedAt: iso(-days(1)),
  },
  {
    id: "material-proj-ready-inspection-drywall-screws",
    projectId: "proj-ready-inspection",
    phaseId: "proj-ready-inspection-phase-drywall",
    itemKey: "one_and_quarter_coarse_thread_screws",
    quantity: 18,
    updatedAt: iso(-days(2)),
  },
  {
    id: "material-proj-ready-inspection-drywall-adhesive",
    projectId: "proj-ready-inspection",
    phaseId: "proj-ready-inspection-phase-drywall",
    itemKey: "drywall_adhesive",
    quantity: 10,
    updatedAt: iso(-days(2)),
  },
  {
    id: "material-proj-site-blocked-drywall-half-inch-regular-board",
    projectId: "proj-site-blocked",
    phaseId: "proj-site-blocked-phase-drywall",
    itemKey: "half_inch_regular_board",
    quantity: 58,
    updatedAt: iso(-days(2)),
  },
  {
    id: "material-proj-site-blocked-drywall-type-x-board",
    projectId: "proj-site-blocked",
    phaseId: "proj-site-blocked-phase-drywall",
    itemKey: "type_x_board",
    quantity: 22,
    updatedAt: iso(-days(2)),
  },
  {
    id: "material-proj-finishing-active-finishing-yellow-mud-box",
    projectId: "proj-finishing-active",
    phaseId: "proj-finishing-active-phase-finishing",
    itemKey: "yellow_mud_box",
    quantity: 6,
    updatedAt: iso(-days(1)),
  },
  {
    id: "material-proj-stale-clean-insulation-r20-batt",
    projectId: "proj-stale-clean",
    phaseId: "proj-stale-clean-phase-insulation",
    itemKey: "r20_batt",
    quantity: 12,
    updatedAt: iso(-days(20)),
  },
];

export const seedEquipmentLogs: EquipmentLog[] = [
  {
    id: "equipment-proj-active-insulation-baker-scaffold",
    projectId: "proj-active-insulation",
    itemKey: "baker_scaffold",
    quantity: 1,
    updatedAt: iso(-days(2)),
  },
  {
    id: "equipment-proj-active-insulation-extension-ladders",
    projectId: "proj-active-insulation",
    itemKey: "extension_ladders",
    quantity: 2,
    updatedAt: iso(-days(2)),
  },
  {
    id: "equipment-proj-active-insulation-air-scrubbers",
    projectId: "proj-active-insulation",
    itemKey: "air_scrubbers",
    quantity: 1,
    updatedAt: iso(-days(2)),
  },
  {
    id: "equipment-proj-ready-inspection-drywall-lift",
    projectId: "proj-ready-inspection",
    itemKey: "drywall_lift",
    quantity: 1,
    updatedAt: iso(-days(3)),
  },
  {
    id: "equipment-proj-ready-inspection-six-foot-step-ladders",
    projectId: "proj-ready-inspection",
    itemKey: "six_foot_step_ladders",
    quantity: 3,
    updatedAt: iso(-days(3)),
  },
  {
    id: "equipment-proj-site-blocked-portable-heaters",
    projectId: "proj-site-blocked",
    itemKey: "portable_heaters",
    quantity: 2,
    updatedAt: iso(-days(2)),
  },
  {
    id: "equipment-proj-finishing-active-site-lighting",
    projectId: "proj-finishing-active",
    itemKey: "site_lighting",
    quantity: 4,
    updatedAt: iso(-days(1)),
  },
  {
    id: "equipment-proj-finishing-active-air-scrubbers",
    projectId: "proj-finishing-active",
    itemKey: "air_scrubbers",
    quantity: 1,
    updatedAt: iso(-days(1)),
  },
  {
    id: "equipment-proj-stale-clean-baker-scaffold",
    projectId: "proj-stale-clean",
    itemKey: "baker_scaffold",
    quantity: 1,
    updatedAt: iso(-days(20)),
  },
];

export const seedInventoryPickups: InventoryPickup[] = [
  {
    id: "pickup-finishing-active-mixed",
    projectId: "proj-finishing-active",
    pickedUpByUserId: "user-inventory-1",
    items: [
      { kind: "equipment", itemKey: "site_lighting", quantity: 1 },
      { kind: "material", itemKey: "all_purpose_mud", quantity: 2 },
    ],
    note: "Returned excess lighting and mud from south garage.",
    createdAt: iso(-days(1)),
  },
  {
    id: "pickup-ready-inspection-materials",
    projectId: "proj-ready-inspection",
    pickedUpByUserId: "user-inventory-1",
    items: [{ kind: "material", itemKey: "half_inch_regular_board", quantity: 12 }],
    createdAt: iso(-days(2)),
  },
  {
    id: "pickup-overdue-clean-full",
    projectId: "proj-overdue-clean",
    pickedUpByUserId: "user-inventory-1",
    items: [
      { kind: "equipment", itemKey: "drywall_lift", quantity: 1 },
      { kind: "material", itemKey: "yellow_mud_box", quantity: 5 },
    ],
    note: "Full closeout pickup after final walkthrough.",
    createdAt: iso(-days(1)),
  },
];

export const seedNotifications: AppNotification[] = [
  {
    id: "notification-seed-audit-ready-finishing",
    recipientUserId: "user-pm-2",
    type: "inventory_audit_request",
    projectId: "proj-ready-finishing-inspection",
    message: "Dale requested materials and hardware audit for Highland Sage Inspection",
    metadata: {
      auditRequestType: "both",
      requesterUserId: "user-inventory-1",
    },
    createdAt: iso(-days(1)),
  },
  {
    id: "notification-seed-pickup-finishing",
    recipientUserId: "user-pm-1",
    type: "inventory_pickup",
    projectId: "proj-finishing-active",
    message: "Dale picked up materials and hardware from Highland Riverbend Finishing",
    metadata: {
      pickupId: "pickup-finishing-active-mixed",
      pickupKinds: ["materials", "hardware"],
      requesterUserId: "user-inventory-1",
      summary: "Temporary Site Lighting ×1, All-Purpose Mud ×2",
    },
    createdAt: iso(-days(1)),
  },
  {
    id: "notification-seed-phase-end-ready-inspection",
    recipientUserId: "user-pm-1",
    type: "phase_end_due",
    projectId: "proj-ready-inspection",
    message: "Drywall phase ends today for Randall Prairie Duplex",
    metadata: {
      phaseId: "proj-ready-inspection-phase-drywall",
      phaseType: "drywall",
      phaseEndDate: new Date(now).toISOString().slice(0, 10),
    },
    createdAt: iso(0),
  },
];

function gateSeed(projectId: string, key: string): GateSeed {
  return scenarioFor(projectId).gates?.[key] ?? {};
}

function phaseGate(project: Project, phase: Phase, type: "site_check" | "inspection"): Gate {
  const seed = gateSeed(project.id, `${phase.type}-${type}`);
  const createdAt = iso(-days(scenarioFor(project.id).ageDays));
  return {
    id: `${project.id}-gate-${phase.type}-${type === "site_check" ? "site-check" : "inspection"}`,
    projectId: project.id,
    phaseId: phase.id,
    type,
    status: seed.status ?? "not_started",
    completedByUserId: seed.completedByUserId,
    completedAt: seed.completedAt,
    requiredPhotoEvidence: type === "site_check",
    notes: seed.notes,
    createdAt,
    updatedAt: seed.updatedAt ?? seed.completedAt ?? createdAt,
  };
}

export const seedGates: Gate[] = seedProjects.flatMap((project) => {
  const phases = seedPhases.filter((phase) => phase.projectId === project.id);
  const phaseGates = phases.flatMap((phase) => [
    phaseGate(project, phase, "site_check"),
    phaseGate(project, phase, "inspection"),
  ]);
  const atticSeed = gateSeed(project.id, "attic");
  const createdAt = iso(-days(scenarioFor(project.id).ageDays));
  return [
    ...phaseGates,
    {
      id: `${project.id}-gate-attic`,
      projectId: project.id,
      type: "attic_check",
      status: atticSeed.status ?? project.atticCheckStatus,
      completedByUserId: atticSeed.completedByUserId,
      completedAt: atticSeed.completedAt,
      requiredPhotoEvidence: true,
      notes: atticSeed.notes,
      callInDate: atticSeed.callInDate,
      installDate: atticSeed.installDate,
      callInSubcontractorId: atticSeed.callInSubcontractorId,
      createdAt,
      updatedAt: atticSeed.updatedAt ?? atticSeed.completedAt ?? project.updatedAt,
    },
  ];
});

export const seedDeficiencies: Deficiency[] = [
  {
    id: "def-failed-inspection-vapor-barrier",
    projectId: "proj-failed-inspection",
    phaseId: "proj-failed-inspection-phase-insulation",
    title: "Vapor barrier discontinuity",
    description: "Inspector found a critical gap on the west wall vapor barrier.",
    severity: "critical",
    status: "open",
    assignedSubcontractorId: "sub-6",
    createdAt: iso(-days(1)),
    updatedAt: iso(-days(1)),
  },
  {
    id: "def-site-blocked-access",
    projectId: "proj-site-blocked",
    phaseId: "proj-site-blocked-phase-drywall",
    title: "Standing water blocks drywall delivery",
    description: "Service lane must be pumped before drywall boards can be staged.",
    severity: "high",
    status: "in_progress",
    assignedSubcontractorId: "sub-9",
    createdAt: iso(-days(2)),
    updatedAt: iso(-days(1)),
  },
  {
    id: "def-rework-sealant",
    projectId: "proj-deficiency-rework",
    phaseId: "proj-deficiency-rework-phase-insulation",
    title: "Sealant touch-up completed",
    description: "Crew corrected foam sealant gaps and uploaded after photos.",
    severity: "medium",
    status: "resolved",
    assignedSubcontractorId: "sub-7",
    resolvedAt: iso(-days(2)),
    resolvedByUserId: "user-pm-2",
    createdAt: iso(-days(7)),
    updatedAt: iso(-days(2)),
  },
  {
    id: "def-completed-trim-scuff",
    projectId: "proj-completed-archiveable",
    phaseId: "proj-completed-archiveable-phase-finishing",
    title: "Trim scuff closed",
    description: "Minor trim scuff was repaired before client sign-off.",
    severity: "low",
    status: "closed",
    assignedSubcontractorId: "sub-15",
    resolvedAt: iso(-days(12)),
    resolvedByUserId: "user-pm-1",
    createdAt: iso(-days(18)),
    updatedAt: iso(-days(10)),
  },
];

export const seedPhotos: PhotoEvidence[] = [
  {
    id: "photo-active-insulation-site-check",
    projectId: "proj-active-insulation",
    phaseId: "proj-active-insulation-phase-insulation",
    gateId: "proj-active-insulation-gate-insulation-site-check",
    purpose: "site_check",
    objectKey: "seed/active-insulation/site-check.jpg",
    contentHash: "seed-active-insulation-site",
    mimeType: "image/jpeg",
    fileSizeBytes: 524288,
    status: "confirmed",
    uploadedByUserId: "user-pm-2",
    createdAt: iso(-days(16)),
    updatedAt: iso(-days(16)),
  },
  {
    id: "photo-ready-inspection-drywall-site-check",
    projectId: "proj-ready-inspection",
    phaseId: "proj-ready-inspection-phase-drywall",
    gateId: "proj-ready-inspection-gate-drywall-site-check",
    purpose: "site_check",
    objectKey: "seed/ready-inspection/drywall-site-check.jpg",
    contentHash: "seed-ready-drywall-site",
    mimeType: "image/jpeg",
    fileSizeBytes: 612000,
    status: "confirmed",
    uploadedByUserId: "user-pm-1",
    createdAt: iso(-days(12)),
    updatedAt: iso(-days(12)),
  },
  {
    id: "photo-site-blocked-access",
    projectId: "proj-site-blocked",
    phaseId: "proj-site-blocked-phase-drywall",
    gateId: "proj-site-blocked-gate-drywall-site-check",
    deficiencyId: "def-site-blocked-access",
    purpose: "deficiency_before",
    objectKey: "seed/site-blocked/access-before.jpg",
    contentHash: "seed-site-blocked-access",
    mimeType: "image/jpeg",
    fileSizeBytes: 734000,
    status: "confirmed",
    uploadedByUserId: "user-pm-2",
    createdAt: iso(-days(2)),
    updatedAt: iso(-days(2)),
  },
  {
    id: "photo-failed-inspection-before",
    projectId: "proj-failed-inspection",
    phaseId: "proj-failed-inspection-phase-insulation",
    gateId: "proj-failed-inspection-gate-insulation-inspection",
    deficiencyId: "def-failed-inspection-vapor-barrier",
    purpose: "deficiency_before",
    objectKey: "seed/failed-inspection/vapor-before.jpg",
    contentHash: "seed-failed-vapor-before",
    mimeType: "image/jpeg",
    fileSizeBytes: 812000,
    status: "confirmed",
    uploadedByUserId: "user-pm-1",
    createdAt: iso(-days(1)),
    updatedAt: iso(-days(1)),
  },
  {
    id: "photo-rework-before",
    projectId: "proj-deficiency-rework",
    phaseId: "proj-deficiency-rework-phase-insulation",
    gateId: "proj-deficiency-rework-gate-insulation-inspection",
    deficiencyId: "def-rework-sealant",
    purpose: "deficiency_before",
    objectKey: "seed/deficiency-rework/sealant-before.jpg",
    contentHash: "seed-rework-before",
    mimeType: "image/jpeg",
    fileSizeBytes: 702000,
    status: "confirmed",
    uploadedByUserId: "user-pm-2",
    createdAt: iso(-days(7)),
    updatedAt: iso(-days(7)),
  },
  {
    id: "photo-rework-after",
    projectId: "proj-deficiency-rework",
    phaseId: "proj-deficiency-rework-phase-insulation",
    deficiencyId: "def-rework-sealant",
    purpose: "deficiency_after",
    objectKey: "seed/deficiency-rework/sealant-after.jpg",
    contentHash: "seed-rework-after",
    mimeType: "image/jpeg",
    fileSizeBytes: 698000,
    status: "confirmed",
    uploadedByUserId: "user-pm-2",
    createdAt: iso(-days(2)),
    updatedAt: iso(-days(2)),
  },
  {
    id: "photo-finishing-general",
    projectId: "proj-finishing-active",
    phaseId: "proj-finishing-active-phase-finishing",
    purpose: "general",
    objectKey: "seed/finishing-active/general-progress.jpg",
    contentHash: "seed-finishing-general",
    mimeType: "image/jpeg",
    fileSizeBytes: 645000,
    status: "confirmed",
    uploadedByUserId: "user-pm-1",
    createdAt: iso(-days(3)),
    updatedAt: iso(-days(3)),
  },
  {
    id: "photo-ready-complete-attic",
    projectId: "proj-ready-complete",
    gateId: "proj-ready-complete-gate-attic",
    purpose: "attic_check",
    objectKey: "seed/ready-complete/attic.jpg",
    contentHash: "seed-ready-complete-attic",
    mimeType: "image/jpeg",
    fileSizeBytes: 654321,
    status: "confirmed",
    uploadedByUserId: "user-pm-2",
    createdAt: iso(-days(3)),
    updatedAt: iso(-days(3)),
  },
  {
    id: "photo-completed-inspection",
    projectId: "proj-completed-archiveable",
    phaseId: "proj-completed-archiveable-phase-finishing",
    gateId: "proj-completed-archiveable-gate-finishing-inspection",
    purpose: "inspection",
    objectKey: "seed/completed-archiveable/finishing-inspection.jpg",
    contentHash: "seed-completed-inspection",
    mimeType: "image/jpeg",
    fileSizeBytes: 688000,
    status: "confirmed",
    uploadedByUserId: "user-pm-1",
    createdAt: iso(-days(16)),
    updatedAt: iso(-days(16)),
  },
  {
    id: "photo-completed-attic",
    projectId: "proj-completed-archiveable",
    gateId: "proj-completed-archiveable-gate-attic",
    purpose: "attic_check",
    objectKey: "seed/completed-archiveable/attic.jpg",
    contentHash: "seed-completed-attic",
    mimeType: "image/jpeg",
    fileSizeBytes: 701000,
    status: "confirmed",
    uploadedByUserId: "user-pm-1",
    createdAt: iso(-days(15)),
    updatedAt: iso(-days(15)),
  },
  {
    id: "photo-archived-attic",
    projectId: "proj-archived-history",
    gateId: "proj-archived-history-gate-attic",
    purpose: "attic_check",
    objectKey: "seed/archived-history/attic.jpg",
    contentHash: "seed-archived-attic",
    mimeType: "image/jpeg",
    fileSizeBytes: 590000,
    status: "confirmed",
    uploadedByUserId: "user-pm-2",
    createdAt: iso(-days(83)),
    updatedAt: iso(-days(83)),
  },
  {
    id: "photo-active-insulation-3480",
    projectId: "proj-active-insulation",
    phaseId: "proj-active-insulation-phase-insulation",
    purpose: "general",
    objectKey: "seed/active-insulation/IMG_3480.jpg",
    contentHash: "seed-active-insulation-3480",
    mimeType: "image/jpeg",
    fileSizeBytes: 612000,
    status: "confirmed",
    uploadedByUserId: "user-pm-2",
    createdAt: iso(-days(14)),
    updatedAt: iso(-days(14)),
  },
  {
    id: "photo-active-insulation-3487",
    projectId: "proj-active-insulation",
    phaseId: "proj-active-insulation-phase-insulation",
    purpose: "general",
    objectKey: "seed/active-insulation/IMG_3487.jpg",
    contentHash: "seed-active-insulation-3487",
    mimeType: "image/jpeg",
    fileSizeBytes: 598000,
    status: "confirmed",
    uploadedByUserId: "user-pm-2",
    createdAt: iso(-days(12)),
    updatedAt: iso(-days(12)),
  },
  {
    id: "photo-failed-inspection-3570",
    projectId: "proj-failed-inspection",
    phaseId: "proj-failed-inspection-phase-insulation",
    purpose: "general",
    objectKey: "seed/failed-inspection/IMG_3570.jpg",
    contentHash: "seed-failed-inspection-3570",
    mimeType: "image/jpeg",
    fileSizeBytes: 576000,
    status: "confirmed",
    uploadedByUserId: "user-pm-1",
    createdAt: iso(-days(3)),
    updatedAt: iso(-days(3)),
  },
  {
    id: "photo-deficiency-rework-3700",
    projectId: "proj-deficiency-rework",
    phaseId: "proj-deficiency-rework-phase-insulation",
    purpose: "general",
    objectKey: "seed/deficiency-rework/IMG_3700.jpg",
    contentHash: "seed-deficiency-rework-3700",
    mimeType: "image/jpeg",
    fileSizeBytes: 603000,
    status: "confirmed",
    uploadedByUserId: "user-pm-2",
    createdAt: iso(-days(5)),
    updatedAt: iso(-days(5)),
  },
  {
    id: "photo-deficiency-rework-5020",
    projectId: "proj-deficiency-rework",
    phaseId: "proj-deficiency-rework-phase-insulation",
    purpose: "general",
    objectKey: "seed/deficiency-rework/IMG_5020.jpg",
    contentHash: "seed-deficiency-rework-5020",
    mimeType: "image/jpeg",
    fileSizeBytes: 589000,
    status: "confirmed",
    uploadedByUserId: "user-pm-2",
    createdAt: iso(-days(4)),
    updatedAt: iso(-days(4)),
  },
  {
    id: "photo-ready-inspection-3659",
    projectId: "proj-ready-inspection",
    phaseId: "proj-ready-inspection-phase-drywall",
    purpose: "general",
    objectKey: "seed/ready-inspection/IMG_3659.jpg",
    contentHash: "seed-ready-inspection-3659",
    mimeType: "image/jpeg",
    fileSizeBytes: 624000,
    status: "confirmed",
    uploadedByUserId: "user-pm-1",
    createdAt: iso(-days(10)),
    updatedAt: iso(-days(10)),
  },
  {
    id: "photo-ready-inspection-3908",
    projectId: "proj-ready-inspection",
    phaseId: "proj-ready-inspection-phase-drywall",
    purpose: "general",
    objectKey: "seed/ready-inspection/IMG_3908.jpg",
    contentHash: "seed-ready-inspection-3908",
    mimeType: "image/jpeg",
    fileSizeBytes: 635000,
    status: "confirmed",
    uploadedByUserId: "user-pm-1",
    createdAt: iso(-days(8)),
    updatedAt: iso(-days(8)),
  },
  {
    id: "photo-site-blocked-351212254",
    projectId: "proj-site-blocked",
    phaseId: "proj-site-blocked-phase-drywall",
    purpose: "general",
    objectKey: "seed/site-blocked/camphoto_351212254.jpg",
    contentHash: "seed-site-blocked-351212254",
    mimeType: "image/jpeg",
    fileSizeBytes: 648000,
    status: "confirmed",
    uploadedByUserId: "user-pm-2",
    createdAt: iso(-days(4)),
    updatedAt: iso(-days(4)),
  },
  {
    id: "photo-site-blocked-6626",
    projectId: "proj-site-blocked",
    phaseId: "proj-site-blocked-phase-drywall",
    purpose: "general",
    objectKey: "seed/site-blocked/photo-6626.jpg",
    contentHash: "seed-site-blocked-6626",
    mimeType: "image/jpeg",
    fileSizeBytes: 671000,
    status: "confirmed",
    uploadedByUserId: "user-pm-2",
    createdAt: iso(-days(3)),
    updatedAt: iso(-days(3)),
  },
  {
    id: "photo-site-blocked-9075",
    projectId: "proj-site-blocked",
    phaseId: "proj-site-blocked-phase-drywall",
    purpose: "general",
    objectKey: "seed/site-blocked/photo-9075.jpg",
    contentHash: "seed-site-blocked-9075",
    mimeType: "image/jpeg",
    fileSizeBytes: 692000,
    status: "confirmed",
    uploadedByUserId: "user-pm-2",
    createdAt: iso(-days(1)),
    updatedAt: iso(-days(1)),
  },
  {
    id: "photo-finishing-active-4467",
    projectId: "proj-finishing-active",
    phaseId: "proj-finishing-active-phase-finishing",
    purpose: "general",
    objectKey: "seed/finishing-active/IMG_4467.jpg",
    contentHash: "seed-finishing-active-4467",
    mimeType: "image/jpeg",
    fileSizeBytes: 658000,
    status: "confirmed",
    uploadedByUserId: "user-pm-1",
    createdAt: iso(-days(6)),
    updatedAt: iso(-days(6)),
  },
  {
    id: "photo-finishing-active-4505",
    projectId: "proj-finishing-active",
    phaseId: "proj-finishing-active-phase-finishing",
    purpose: "general",
    objectKey: "seed/finishing-active/IMG_4505.jpg",
    contentHash: "seed-finishing-active-4505",
    mimeType: "image/jpeg",
    fileSizeBytes: 642000,
    status: "confirmed",
    uploadedByUserId: "user-pm-1",
    createdAt: iso(-days(5)),
    updatedAt: iso(-days(5)),
  },
  {
    id: "photo-finishing-active-4527",
    projectId: "proj-finishing-active",
    phaseId: "proj-finishing-active-phase-finishing",
    purpose: "general",
    objectKey: "seed/finishing-active/IMG_4527.jpg",
    contentHash: "seed-finishing-active-4527",
    mimeType: "image/jpeg",
    fileSizeBytes: 667000,
    status: "confirmed",
    uploadedByUserId: "user-pm-1",
    createdAt: iso(-days(4)),
    updatedAt: iso(-days(4)),
  },
  {
    id: "photo-finishing-active-4545",
    projectId: "proj-finishing-active",
    phaseId: "proj-finishing-active-phase-finishing",
    purpose: "general",
    objectKey: "seed/finishing-active/IMG_4545.jpg",
    contentHash: "seed-finishing-active-4545",
    mimeType: "image/jpeg",
    fileSizeBytes: 655000,
    status: "confirmed",
    uploadedByUserId: "user-pm-1",
    createdAt: iso(-days(2)),
    updatedAt: iso(-days(2)),
  },
  {
    id: "photo-ready-complete-foam-joist-2",
    projectId: "proj-ready-complete",
    phaseId: "proj-ready-complete-phase-insulation",
    purpose: "general",
    objectKey: "seed/ready-complete/foam-joist-2.jpg",
    contentHash: "seed-ready-complete-foam-joist-2",
    mimeType: "image/jpeg",
    fileSizeBytes: 581000,
    status: "confirmed",
    uploadedByUserId: "user-pm-2",
    createdAt: iso(-days(6)),
    updatedAt: iso(-days(6)),
  },
  {
    id: "photo-ready-complete-framing-3007",
    projectId: "proj-ready-complete",
    phaseId: "proj-ready-complete-phase-insulation",
    purpose: "general",
    objectKey: "seed/ready-complete/IMG_3007.jpg",
    contentHash: "seed-ready-complete-framing-3007",
    mimeType: "image/jpeg",
    fileSizeBytes: 594000,
    status: "confirmed",
    uploadedByUserId: "user-pm-2",
    createdAt: iso(-days(5)),
    updatedAt: iso(-days(5)),
  },
  {
    id: "photo-ready-complete-framing-3055",
    projectId: "proj-ready-complete",
    phaseId: "proj-ready-complete-phase-drywall",
    purpose: "general",
    objectKey: "seed/ready-complete/IMG_3055.jpg",
    contentHash: "seed-ready-complete-framing-3055",
    mimeType: "image/jpeg",
    fileSizeBytes: 608000,
    status: "confirmed",
    uploadedByUserId: "user-pm-2",
    createdAt: iso(-days(4)),
    updatedAt: iso(-days(4)),
  },
  {
    id: "photo-ready-complete-framing-3186",
    projectId: "proj-ready-complete",
    phaseId: "proj-ready-complete-phase-finishing",
    purpose: "general",
    objectKey: "seed/ready-complete/IMG_3186.jpg",
    contentHash: "seed-ready-complete-framing-3186",
    mimeType: "image/jpeg",
    fileSizeBytes: 615000,
    status: "confirmed",
    uploadedByUserId: "user-pm-2",
    createdAt: iso(-days(3)),
    updatedAt: iso(-days(3)),
  },
  {
    id: "photo-completed-4458",
    projectId: "proj-completed-archiveable",
    phaseId: "proj-completed-archiveable-phase-finishing",
    purpose: "general",
    objectKey: "seed/completed-archiveable/IMG_4458.jpg",
    contentHash: "seed-completed-4458",
    mimeType: "image/jpeg",
    fileSizeBytes: 627000,
    status: "confirmed",
    uploadedByUserId: "user-pm-1",
    createdAt: iso(-days(14)),
    updatedAt: iso(-days(14)),
  },
  {
    id: "photo-archived-finishing-site-check",
    projectId: "proj-archived-history",
    phaseId: "proj-archived-history-phase-finishing",
    purpose: "general",
    objectKey: "seed/archived-history/finishing-site-check.jpg",
    contentHash: "seed-archived-finishing-site-check",
    mimeType: "image/jpeg",
    fileSizeBytes: 639000,
    status: "confirmed",
    uploadedByUserId: "user-pm-2",
    createdAt: iso(-days(80)),
    updatedAt: iso(-days(80)),
  },
  {
    id: "photo-archived-9151",
    projectId: "proj-archived-history",
    phaseId: "proj-archived-history-phase-finishing",
    purpose: "general",
    objectKey: "seed/archived-history/photo-9151.jpg",
    contentHash: "seed-archived-9151",
    mimeType: "image/jpeg",
    fileSizeBytes: 651000,
    status: "confirmed",
    uploadedByUserId: "user-pm-2",
    createdAt: iso(-days(78)),
    updatedAt: iso(-days(78)),
  },
  {
    id: "photo-archived-9172",
    projectId: "proj-archived-history",
    phaseId: "proj-archived-history-phase-finishing",
    purpose: "general",
    objectKey: "seed/archived-history/photo-9172.jpg",
    contentHash: "seed-archived-9172",
    mimeType: "image/jpeg",
    fileSizeBytes: 663000,
    status: "confirmed",
    uploadedByUserId: "user-pm-2",
    createdAt: iso(-days(76)),
    updatedAt: iso(-days(76)),
  },
  {
    id: "photo-archived-9314",
    projectId: "proj-archived-history",
    phaseId: "proj-archived-history-phase-finishing",
    purpose: "general",
    objectKey: "seed/archived-history/photo-9314.jpg",
    contentHash: "seed-archived-9314",
    mimeType: "image/jpeg",
    fileSizeBytes: 675000,
    status: "confirmed",
    uploadedByUserId: "user-pm-2",
    createdAt: iso(-days(74)),
    updatedAt: iso(-days(74)),
  },
  {
    id: "photo-pending-active-insulation-poly",
    projectId: "proj-active-insulation",
    phaseId: "proj-active-insulation-phase-insulation",
    purpose: "general",
    objectKey: "seed/active-insulation/pending-poly.jpg",
    contentHash: "seed-pending-poly",
    mimeType: "image/jpeg",
    fileSizeBytes: 512000,
    status: "pending_upload",
    uploadedByUserId: "user-pm-2",
    createdAt: iso(-days(1)),
    updatedAt: iso(-days(1)),
  },
  {
    id: "photo-uploaded-ready-finishing",
    projectId: "proj-ready-finishing-inspection",
    phaseId: "proj-ready-finishing-inspection-phase-finishing",
    gateId: "proj-ready-finishing-inspection-gate-finishing-site-check",
    purpose: "site_check",
    objectKey: "seed/ready-finishing/uploaded-site-check.jpg",
    contentHash: "seed-uploaded-ready-finishing",
    mimeType: "image/jpeg",
    fileSizeBytes: 631000,
    status: "uploaded",
    uploadedByUserId: "user-pm-2",
    createdAt: iso(-days(4)),
    updatedAt: iso(-days(4)),
  },
  {
    id: "photo-failed-site-blocked-delivery",
    projectId: "proj-site-blocked",
    phaseId: "proj-site-blocked-phase-drywall",
    deficiencyId: "def-site-blocked-access",
    purpose: "deficiency_after",
    objectKey: "seed/site-blocked/failed-delivery-after.jpg",
    contentHash: "seed-failed-site-blocked-delivery",
    mimeType: "image/jpeg",
    fileSizeBytes: 480000,
    status: "failed",
    uploadedByUserId: "user-pm-2",
    createdAt: iso(-days(1)),
    updatedAt: iso(-days(1)),
  },
];

function audit(
  id: string,
  entityType: AuditEvent["entityType"],
  entityId: string,
  action: string,
  actorUserId: string,
  ageDays: number,
  extra: Partial<AuditEvent> = {},
): AuditEvent {
  return {
    id,
    entityType,
    entityId,
    action,
    actorUserId,
    createdAt: iso(-days(ageDays)),
    ...extra,
  };
}

export const seedAuditEvents: AuditEvent[] = [
  audit("audit-create-draft-new-home", "project", "proj-draft-new-home", "create_project", "user-admin", 4),
  audit("audit-notes-draft-new-home", "project", "proj-draft-new-home", "project_notes_updated", "user-pm-1", 2),
  audit("audit-create-active-insulation", "project", "proj-active-insulation", "create_project", "user-admin", 25),
  audit("audit-activate-active-insulation", "project", "proj-active-insulation", "activate_project", "user-pm-2", 18, { previousValue: "draft", nextValue: "active" }),
  audit("audit-active-insulation-site-check", "gate", "proj-active-insulation-gate-insulation-site-check", "site_check_completed", "user-pm-2", 16, { metadata: { phaseId: "proj-active-insulation-phase-insulation", notes: "Insulation site check passed." } }),
  audit("audit-active-insulation-photo", "photo_evidence", "photo-active-insulation-site-check", "photo_uploaded", "user-pm-2", 16),
  audit("audit-active-insulation-attic", "gate", "proj-active-insulation-gate-attic", "attic_gate_updated", "user-pm-2", 4),
  audit("audit-create-ready-inspection", "project", "proj-ready-inspection", "create_project", "user-admin", 40),
  audit("audit-ready-inspection-activate", "project", "proj-ready-inspection", "activate_project", "user-pm-1", 32, { previousValue: "draft", nextValue: "active" }),
  audit("audit-ready-drywall-site", "gate", "proj-ready-inspection-gate-drywall-site-check", "site_check_completed", "user-pm-1", 12),
  audit("audit-ready-drywall-phase", "phase", "proj-ready-inspection-phase-drywall", "phase_ready_for_inspection", "user-pm-1", 1),
  audit("audit-create-site-blocked", "project", "proj-site-blocked", "create_project", "user-admin", 34),
  audit("audit-site-blocked-activate", "project", "proj-site-blocked", "activate_project", "user-pm-2", 26, { previousValue: "draft", nextValue: "active" }),
  audit("audit-site-blocked-gate", "gate", "proj-site-blocked-gate-drywall-site-check", "site_check_blocked", "user-pm-2", 1, { metadata: { phaseId: "proj-site-blocked-phase-drywall", notes: "Standing water blocks material delivery." } }),
  audit("audit-site-blocked-deficiency", "deficiency", "def-site-blocked-access", "create_deficiency", "user-pm-2", 2),
  audit("audit-create-failed-inspection", "project", "proj-failed-inspection", "create_project", "user-admin", 31),
  audit("audit-failed-inspection-site", "gate", "proj-failed-inspection-gate-insulation-site-check", "site_check_completed", "user-pm-1", 18),
  audit("audit-failed-inspection-gate", "gate", "proj-failed-inspection-gate-insulation-inspection", "inspection_failed", "user-pm-1", 1, { metadata: { phaseId: "proj-failed-inspection-phase-insulation", inspectorName: "Dana Frost", notes: "Vapor barrier discontinuity." } }),
  audit("audit-failed-inspection-deficiency", "deficiency", "def-failed-inspection-vapor-barrier", "create_deficiency", "user-pm-1", 1),
  audit("audit-create-rework", "project", "proj-deficiency-rework", "create_project", "user-admin", 48),
  audit("audit-rework-failed", "gate", "proj-deficiency-rework-gate-insulation-inspection", "inspection_failed", "user-pm-2", 7),
  audit("audit-rework-resolved", "deficiency", "def-rework-sealant", "updated", "user-pm-2", 2, { previousValue: { status: "open" }, nextValue: { status: "resolved" } }),
  audit("audit-rework-after-photo", "photo_evidence", "photo-rework-after", "photo_uploaded", "user-pm-2", 2),
  audit("audit-create-finishing-active", "project", "proj-finishing-active", "create_project", "user-admin", 60),
  audit("audit-finishing-sub-assigned", "phase", "proj-finishing-active-phase-finishing", "subcontractor_assigned", "user-pm-1", 15, { metadata: { subcontractorId: "sub-17", subcontractorName: "Kevin Lee" } }),
  audit("audit-finishing-general-photo", "photo_evidence", "photo-finishing-general", "photo_uploaded", "user-pm-1", 3),
  audit("audit-create-ready-complete", "project", "proj-ready-complete", "create_project", "user-admin", 76),
  audit("audit-ready-complete-inspection", "gate", "proj-ready-complete-gate-finishing-inspection", "inspection_passed", "user-pm-2", 3, { metadata: { phaseId: "proj-ready-complete-phase-finishing", inspectorName: "Riley Stone" } }),
  audit("audit-ready-complete-attic", "gate", "proj-ready-complete-gate-attic", "attic_gate_updated", "user-pm-2", 3),
  audit("audit-ready-complete-project", "project", "proj-ready-complete", "complete_project", "user-pm-2", 1, { previousValue: "active", nextValue: "completed" }),
  audit("audit-create-completed", "project", "proj-completed-archiveable", "create_project", "user-admin", 106),
  audit("audit-completed-project", "project", "proj-completed-archiveable", "complete_project", "user-pm-1", 10, { previousValue: "active", nextValue: "completed" }),
  audit("audit-completed-deficiency-closed", "deficiency", "def-completed-trim-scuff", "updated", "user-pm-1", 10, { previousValue: { status: "resolved" }, nextValue: { status: "closed" } }),
  audit("audit-create-archived", "project", "proj-archived-history", "create_project", "user-admin", 160),
  audit("audit-complete-archived", "project", "proj-archived-history", "complete_project", "user-pm-2", 82, { previousValue: "active", nextValue: "completed" }),
  audit("audit-archive-history", "project", "proj-archived-history", "archive_project", "user-admin", 80, { previousValue: "completed", nextValue: "archived" }),
  audit("audit-active-insulation-photo-3480", "photo_evidence", "photo-active-insulation-3480", "photo_uploaded", "user-pm-2", 14),
  audit("audit-active-insulation-photo-3487", "photo_evidence", "photo-active-insulation-3487", "photo_uploaded", "user-pm-2", 12),
  audit("audit-failed-inspection-photo-3570", "photo_evidence", "photo-failed-inspection-3570", "photo_uploaded", "user-pm-1", 3),
  audit("audit-rework-photo-3700", "photo_evidence", "photo-deficiency-rework-3700", "photo_uploaded", "user-pm-2", 5),
  audit("audit-rework-photo-5020", "photo_evidence", "photo-deficiency-rework-5020", "photo_uploaded", "user-pm-2", 4),
  audit("audit-ready-inspection-photo-3659", "photo_evidence", "photo-ready-inspection-3659", "photo_uploaded", "user-pm-1", 10),
  audit("audit-ready-inspection-photo-3908", "photo_evidence", "photo-ready-inspection-3908", "photo_uploaded", "user-pm-1", 8),
  audit("audit-site-blocked-photo-351212254", "photo_evidence", "photo-site-blocked-351212254", "photo_uploaded", "user-pm-2", 4),
  audit("audit-site-blocked-photo-6626", "photo_evidence", "photo-site-blocked-6626", "photo_uploaded", "user-pm-2", 3),
  audit("audit-site-blocked-photo-9075", "photo_evidence", "photo-site-blocked-9075", "photo_uploaded", "user-pm-2", 1),
  audit("audit-finishing-active-photo-4467", "photo_evidence", "photo-finishing-active-4467", "photo_uploaded", "user-pm-1", 6),
  audit("audit-finishing-active-photo-4505", "photo_evidence", "photo-finishing-active-4505", "photo_uploaded", "user-pm-1", 5),
  audit("audit-finishing-active-photo-4527", "photo_evidence", "photo-finishing-active-4527", "photo_uploaded", "user-pm-1", 4),
  audit("audit-finishing-active-photo-4545", "photo_evidence", "photo-finishing-active-4545", "photo_uploaded", "user-pm-1", 2),
  audit("audit-ready-complete-photo-foam-joist-2", "photo_evidence", "photo-ready-complete-foam-joist-2", "photo_uploaded", "user-pm-2", 6),
  audit("audit-ready-complete-photo-framing-3007", "photo_evidence", "photo-ready-complete-framing-3007", "photo_uploaded", "user-pm-2", 5),
  audit("audit-ready-complete-photo-framing-3055", "photo_evidence", "photo-ready-complete-framing-3055", "photo_uploaded", "user-pm-2", 4),
  audit("audit-ready-complete-photo-framing-3186", "photo_evidence", "photo-ready-complete-framing-3186", "photo_uploaded", "user-pm-2", 3),
  audit("audit-completed-photo-4458", "photo_evidence", "photo-completed-4458", "photo_uploaded", "user-pm-1", 14),
  audit("audit-archived-photo-finishing-site-check", "photo_evidence", "photo-archived-finishing-site-check", "photo_uploaded", "user-pm-2", 80),
  audit("audit-archived-photo-9151", "photo_evidence", "photo-archived-9151", "photo_uploaded", "user-pm-2", 78),
  audit("audit-archived-photo-9172", "photo_evidence", "photo-archived-9172", "photo_uploaded", "user-pm-2", 76),
  audit("audit-archived-photo-9314", "photo_evidence", "photo-archived-9314", "photo_uploaded", "user-pm-2", 74),
  audit("audit-inventory-request-ready-finishing", "project", "proj-ready-finishing-inspection", "inventory_audit_requested", "user-inventory-1", 1, { metadata: { auditRequestType: "both", recipientUserId: "user-pm-2", notificationId: "notification-seed-audit-ready-finishing" } }),
  audit("audit-inventory-pickup-finishing", "project", "proj-finishing-active", "inventory_picked_up", "user-inventory-1", 1, { metadata: { pickupId: "pickup-finishing-active-mixed", notificationId: "notification-seed-pickup-finishing", summary: "Temporary Site Lighting ×1, All-Purpose Mud ×2", note: "Returned excess lighting and mud from south garage." } }),
  audit("audit-inventory-pickup-ready-inspection", "project", "proj-ready-inspection", "inventory_picked_up", "user-inventory-1", 2, { metadata: { pickupId: "pickup-ready-inspection-materials", summary: "1/2\" Regular Board ×12" } }),
  audit("audit-inventory-pickup-overdue", "project", "proj-overdue-clean", "inventory_picked_up", "user-inventory-1", 1, { metadata: { pickupId: "pickup-overdue-clean-full", summary: "Drywall Lifts ×1, Yellow Mud Box ×5", note: "Full closeout pickup after final walkthrough." } }),
  audit("audit-seed-materials-ready-inspection", "phase", "proj-ready-inspection-phase-drywall", "materials_updated", "user-pm-1", 2, { metadata: { inventoryChanges: [{ itemKey: "half_inch_regular_board", label: "1/2\" Regular Board", previousQuantity: 108, quantity: 96 }] } }),
  audit("audit-seed-hardware-site-blocked", "project", "proj-site-blocked", "hardware_updated", "user-pm-2", 2, { metadata: { inventoryChanges: [{ itemKey: "portable_heaters", label: "Portable Heaters", previousQuantity: 0, quantity: 2 }] } }),
  audit("audit-create-empty-client", "client_record", "client-5", "create_client", "user-admin", 12),
  audit("audit-create-backup-admin", "user", "user-admin-2", "create_user", "user-admin", 80),
  audit("audit-deactivate-inactive-pm", "user", "user-pm-inactive", "deactivated", "user-admin", 40),
  audit("audit-today-notes-finishing", "project", "proj-finishing-active", "project_notes_updated", "user-pm-1", 0),
  audit("audit-today-photo-finishing", "photo_evidence", "photo-finishing-general", "photo_uploaded", "user-pm-1", 0),
  audit("audit-today-attic-ready-inspection", "gate", "proj-ready-inspection-gate-attic", "attic_gate_updated", "user-pm-1", 0),
].sort((a, b) => (a.createdAt < b.createdAt ? 1 : -1));
